### PR TITLE
Reorganized python packaging, removed example gatkpython package, removed duplicate gCNV python scripts.

### LINKED ISSUE #4054: Repackage `gcnvkernel` and move the CLI python scripts to Java resources
Also, update the last paragraph of `gcnvkernel/README.txt` to mention that python CLI scripts are located at `gatk/src/main/resources/org/broadinstitute/hellbender/tools/copynumber/`.

### LINKED ISSUE #4064: new Germline CNV wdl test are too slow, causing travis failures
The newly enabled GermlineCNV wdl tests seem to take ~1 hour 8 minutes.  The maximum timeout for our travis jobs is 1 hour 10 minutes.  This is causing random failures.  It's also the slowest of our matrix entry by a large margin which makes our tests even slower than they are.  Can these be speed up?

Alternatively we may need to talk to the travis people and get a special dispensation to increase our job timeouts even farther.

### PR DESCRIPTION
**Pull request by samuelklee**
Just the last commit.
 
Closes #4054.
Closes #4064.

### CODE REVIEW

**Comment by samuelklee** [comment]
@cmnbroad Can you take a quick look at the last commit and see if the organization is to your liking?

**Comment by cmnbroad** [comment]
@samuelklee @mbabadi The Python structure looks fine to me, assuming the setup part works (I'd like to look at the java front ends too, but won't have time to do that today).

However, have you created this conda env on a mac ? It looks like its been working in travis, but when I try to create it locally I get:

ResolvePackageNotFound: 
  - intel-openmp 2018.0.0 hc7b2577_8

**Comment by samuelklee** [comment]
Good catch.  I think hc7b2577_8 might be specific for linux64.  We can try removing that hash, but I don't have a mac, so I can't test this.

**Comment by samuelklee** [comment]
@cmnbroad I cleaned up some of the hashes and was able to create the conda environment locally.  Can you try on your mac?  We'll see if tests pass on Travis as well, then merge if all is good.

**Comment by cmnbroad** [comment]
Looks like none of these resolve on a mac:

- intel-openmp=2018.0.0=hc7b2577_8
- libgcc-ng=7.2.0=h7cc24e2_2
- mkl=2018.0.1=h19d6760_4
- mkl-service=1.1.2=py36h17a0993_4
- numpy=1.13.3=py36ha12f23b_0

Changing them to this works:

- intel-openmp=2018.0.0
- mkl=2018.0.1
- mkl-service=1.1.2
- numpy=1.13.3

but that leaves out libgcc completely because

- libgcc-ng=7.2.0

fails.

**Comment by cmnbroad** [comment]
BTW, by "works" I mean I can create the env. I didn't try running the tests with the resulting env.

**Comment by cmnbroad** [comment]
@samuelklee Hold on - just saw the last message. Let me try using your .yml.

**Comment by samuelklee** [comment]
@cmnbroad Hmm, I basically just did what you did.  Not sure what the deal is with libgcc-ng, I'll look into it.

**Comment by cmnbroad** [comment]
Yeah, I still see this:
 ResolvePackageNotFound: 
  - libgcc-ng 7.2.0*

**Comment by samuelklee** [comment]
@cmnbroad Yeah, it looks like libgcc-ng is not available for osx64 at all.  There is libgcc, but even that is only at 4.8.5 for osx64 (and at 7.2.0 for linux32/64).

@mbabadi Do you know what the difference is between libgcc-ng and libgcc?  (Even if libgcc is an acceptable subsititute, I'm not sure how to peg the different version numbers across linux and osx, and I'm not sure if there are differences between them.)

Are we going to require use of the Docker?

**Comment by samuelklee** [comment]
@lbergelson any ideas?

**Comment by samuelklee** [comment]
@lbergelson Looks like the CPU thing didn’t work.  Left it in anyway.  Hopefully that extra 30 minutes helps out!

**Pull request merged**
