### PR TITLE
Add gatk-launch --list, make ./gatk-launch, ./gatk-launch --help, and ./gatk-launch -h all print help for the script itself

### LINKED ISSUE #1331: gatk-launch -h doesn't always show the right info
If you haven't "built" the wrapper script, it complains.  Strictly speaking, if you're only ever going to use Spark, you don't need the wrapper.  The check should only happen if you choose the local walker impl.

```
[ec2-user@ip-10-1-1-71 gatk-4.alpha.rc1]$ ./gatk-launch -h
Missing GATK wrapper script: /home/ec2-user/gatk-4.alpha.rc1/build/install/gatk/bin/gatk
To generate the wrapper run:

    /home/ec2-user/gatk-4.alpha.rc1/gradlew installDist
```

### PR DESCRIPTION
**Pull request by droazen**
The script help output now mentions --list.

Resolves #1331

### CODE REVIEW

**Comment by droazen** [comment]
@lbergelson please review

**Comment by lbergelson** [comment]
This needs to modify Main to accept `--list` as well.

**Comment by lbergelson** [comment]
sorry, wasn't paying enough attention.  looks fine

**Comment by laserson** [comment]
lgtm

**Pull request merged**
