### PR TITLE
Updated the ubuntu version for the carrot github action because github dropped support for 18.04

### PR DESCRIPTION
**Pull request by KevinCLydon**

### CODE REVIEW

**Review by lbergelson — APPROVED** [review]
Seems reasonable.  How do we tell if it's working?

**Comment by KevinCLydon** [comment]
That's a good question actually.  I verified it works with another repo, but I'm not sure how much weight that carries.  Even if it doesn't work, it shouldn't make anything worse anyway?

**Comment by KevinCLydon** [comment]
I'll test it with this comment

**Comment by KevinCLydon** [comment]
Success! And I canceled the runs that were hanging waiting for VMs with 18.04

**Pull request merged**
