### PR TITLE
Make extract backwards compatible with the new schema

### PR DESCRIPTION
**Pull request by RoriCremer**
successful run:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/649ee4c9-1afc-473b-b460-2fc88d5f49d4

failing run with the bug:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/f1c952fc-7f05-4468-ae20-1c1cc5b9bf38

AC is:

Cohort builder subcohort extract in AoU and our extract workflow work with both VETS and VQSR callsets, including past callsets. (Note--I did not test in AoU, just on quickstart since the issue doesn't seem to be permission or scale related--see failure reproduced above)

Full extract with past callset & VQSR
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/649ee4c9-1afc-473b-b460-2fc88d5f49d4

Subcohort extract with past callset & VQSR

Full extract with new callset & VETS
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/50ef3073-f618-42ee-b207-73712a783a8a
(note this failed but only on one of the 4 runs and it's based on query cost)

Screenshot 2023-08-25 at 1 22 58 PM

Kevin is able to run latest extract on Delta (still waiting on Kevin, but otherwise the above are all set)

note that there was briefly no "score" col but I dont _think_ we need to be backwards compatible for that as there was no release

### CODE REVIEW

**Comment by mcovarr** [comment]
Can you please have this target `bulk_ingest_staging` rather than `ah_var_store`?

**Review by mcovarr — COMMENTED** [review]
Can you please have this target `bulk_ingest_staging` rather than `ah_var_store`?

**Review by mcovarr — CHANGES_REQUESTED** [review]
Can you please have this target `bulk_ingest_staging` rather than `ah_var_store`?

**Review by mcovarr — APPROVED** [review]

**Review by koncheto-broad — APPROVED** [review]
LGTM!

**Pull request merged**
