### PR TITLE
Update google-cloud-nio to support underscores in bucket names

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Review by droazen — APPROVED** [review]
Looks good, assuming the test case you added fails with the previous version of the NIO library.

**Comment by kshakir** [comment]
@droazen I may also have to bump the shadowJar library... investigating...

**Comment by droazen** [comment]
@kshakir Yes, something is compiled for Java 19 (we are on 17)...

**Comment by lbergelson** [comment]
> You are currently running with version 2.2.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the BigQuery API library.

**Comment by kshakir** [comment]
This PR is on hold until Picard is updated to use the new google libs: https://github.com/broadinstitute/picard/pull/1903

**Comment by kshakir** [comment]
Tests are passing using a snapshot generated while debugging https://github.com/broadinstitute/picard/pull/1904

Folks can review and give feedback. Perhaps we shouldn't merge though unless referencing a library SNAPSHOT is ok or picard 3.0.1 is released.

**Comment by kshakir** [comment]
Tests now running with the Picard 3.1.0 release

**Review by droazen — APPROVED** [review]
This looks fine to me @kshakir , but I recommend asking @lbergelson to take a look at the `build.gradle` changes as well.

**Comment by kshakir** [comment]
Force pushed an update using a freshly released guava which no longer requires pinning mockito.

**Review by lbergelson — APPROVED** [review]
@kshakir L_G_T_M

**Comment by lbergelson** [comment]
Thank you @kshakir

**Pull request merged**
