### PR TITLE
Fixed bug resulting from prefix strings of less than 3 characters when creating temporary files in GermlineCNVCaller and improved documentation of corresponding utility methods.

### LINKED ISSUE #7410: GermlineCNVCaller exception raised from  `createTempFileInDirectory`
### Affected version(s)
- [ ] (GATK) v4.2.1.0

### Description 
Java exception raised when aggregating counts for samples with a name shorter than 3 characters. For example, in the pasted logs, it errors out when processing sample with interval read counts in `94.mkdup.sort.rg.tsv`.

And I found removing the sample from the list of files would avoid the error. 

### Logs:

`
06:49:05.526 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/713.mkdup.sort.rg.tsv (40 / 323)
06:49:07.999 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/252.mkdup.sort.rg.tsv (41 / 323)
06:49:10.433 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/547.mkdup.sort.rg.tsv (42 / 323)
06:49:13.341 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/154.mkdup.sort.rg.tsv (43 / 323)
06:49:15.782 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/651.mkdup.sort.rg.tsv (44 / 323)
06:49:18.251 INFO  GermlineCNVCaller - Aggregating read-count file output/gCNV/bulkDNAseq_BGI/F20FTSAPHT0350_MUSyfqR/count_tsv/94.mkdup.sort.rg.tsv (45 / 323)
06:49:20.605 INFO  GermlineCNVCaller - Shutting down engine
[August 13, 2021 6:49:20 AM GMT] org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller done. Elapsed time: 2.27 minutes.
Runtime.totalMemory()=2076049408
java.lang.IllegalArgumentException: Prefix string too short
        at java.io.File.createTempFile(File.java:2001)
        at org.broadinstitute.hellbender.utils.io.IOUtils.createTempFileInDirectory(IOUtils.java:685)
        at org.broadinstitute.hellbender.utils.io.IOUtils.createTempFile(IOUtils.java:666)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.lambda$writeIntervalSubsetReadCountFiles$1(GermlineCNVCaller.java:434)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.writeIntervalSubsetReadCountFiles(GermlineCNVCaller.java:433)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:323)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)

`
----

### PR DESCRIPTION
**Pull request by samuelklee**
Closes #7410.

### CODE REVIEW

**Comment by samuelklee** [comment]
@mwalker174 super quick one for you. Didn't think it was worth adding a regression test at this point (since this would involve editing sample names in some of the test resources/models), but feel free to file an issue if you think it might be worth addressing later.

**Review by mwalker174 — APPROVED** [review]
Thanks @samuelklee, looks good! It would be nice to have methods calling `File.createTempFile()` automatically amend the filename if the prefix is too short, but that also has edge cases that consuming tools could get into trouble with… I think the parameter doc updates are sufficient here.

**Comment by ruqianl** [comment]
Thanks for fixing this! When is the fix expected to be included in the docker image?

**Comment by samuelklee** [comment]
No problem @ruqianl, thanks again for bringing it to our attention! The fix will be included in the official Docker image in the next release; however, I'm not sure if that will happen imminently, as the last release occurred just 18 days ago and there have only been 10 additional commits in the meantime. @droazen may have a better timeline for you.

I believe there are some nightly Docker builds at https://hub.docker.com/r/broadinstitute/gatk-nightly/, so give it enough time and this fix should show up there (if it hasn't already).

**Comment by ruqianl** [comment]
Thanks, @samuelklee I'd try out the nightly builds.

I have got another question about running multiple shards in parallel by submitting multiple slurm jobs each running GermlineCNVCaller with one shard. That seems to trigger this (`INFO (theano.gof.compilelock`). 

`
INFO (theano.gof.compilelock): Waiting for existing lock by process '62379' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '3632551' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by unknown process (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '62379' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '3633423' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '3633419' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '3633423' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '3633419' (I am process '61988')
INFO (theano.gof.compilelock): To manually release the lock, delete /mnt/beegfs/mccarthy/scratch/general/rlyu/Projects/Snakemake_projects/yeln_2019_spermtyping/.theano/compiledir_Linux-4.18-el8_4.x86_64-x86_64-with-debian-buster-sid-x86_64-3.6.10-64/lock_dir
`

And there isn't a `lock_dir` under the specified path, but there are a bunch of tmp dirs like 

`
tmpxmako3mg
tmpxqfosn7p
tmpxsqfj_t1
`

Would you recommend deleting these folders to release the compiler lock?

**Comment by samuelklee** [comment]
Thanks @ruqianl, you may want to read through the comments at https://github.com/broadinstitute/gatk/issues/6235 and the corresponding PR https://github.com/broadinstitute/gatk/pull/6244. See also the following bit of documentation added in that PR:

> Advanced users may wish to set the THEANO_FLAGS environment variable to override the GATK theano configuration. For example, by running THEANO_FLAGS="base_compiledir=PATH/TO/BASE_COMPILEDIR" gatk GermlineCNVCaller ..., users can specify the theano compilation directory (which is set to $HOME/.theano by default). See theano documentation at https://theano-pymc.readthedocs.io/en/latest/library/config.html.

So you can specify a unique compilation directory for each of your jobs to avoid the compilelock, e.g., `THEANO_FLAGS="base_compiledir=PATH/TO/BASE_COMPILEDIR/FOR/JOB/0" gatk GermlineCNVCaller ...`, `THEANO_FLAGS="base_compiledir=PATH/TO/BASE_COMPILEDIR/FOR/JOB/1" gatk GermlineCNVCaller ...`, etc.

**Comment by ruqianl** [comment]
Great! Thanks for the links! :)

**Pull request merged**
