### PR TITLE
bump to LFS 1.1.1 that fixes a race condition that hurt us

### PR DESCRIPTION
**Pull request by akiezun**
@lbergelson can you look a this?
https://github.com/github/git-lfs/issues/904 is fixed in 1.1.1 so i bumped us to 1.1.1 (i get hit by this bug in https://github.com/broadinstitute/gatk/pull/1555)

### CODE REVIEW

**Comment by lbergelson** [comment]
If tests pass :+1:   I was trying to bump to 1.1.2 in https://github.com/broadinstitute/gatk/compare/lb_update_git_lfs_version, but was running into some problems.

**Comment by akiezun** [comment]
nope, this fails. maybe it's because the go version on travis is 1.4 and git lsf 1.1.1 wants 1.6 ? @lbergelson do you know how to bump go version?

**Comment by lbergelson** [comment]
Instead of bumping the go version I think we might do better just installing the prebuilt binary.  I have an alternate branch where I was trying to bump the git-lfs version and encountering the same problems.  I'm trying to just download the latest version and install it now, so we'll see if that works.

**Comment by akiezun** [comment]
ok, closing this then

**Comment by lbergelson** [comment]
I'm pretty sure this is an lfs bug and not something on our end.  https://github.com/github/git-lfs/issues/1090

**Pull request closed without merging**
