### PR TITLE
Add support for block gzipped files with a .bgz suffix (as well as

### PR DESCRIPTION
**Pull request by tomwhite**
a .gz suffix), see https://github.com/HadoopGenomics/Hadoop-BAM/pull/106.

Also remove spurious debug.

### CODE REVIEW

**Comment by tomwhite** [comment]
@akiezun can you review this please? Small follow on for #1936

**Comment by akiezun** [comment]
thanks @tomwhite. how do I test it?

**Comment by tomwhite** [comment]
@akiezun if you run `CountVariantsSparkIntegrationTest` without the fix you'll see a warning about using gzip. With the fix (this PR) the warning goes away.

**Comment by akiezun** [comment]
thanks. It works. I'd prefer to test for it more directly. Can you examine the stderr in the tests, like this
(change to CountVariantsSparkIntegrationTest .testCountVariantsWithIntervals)
```
        final ByteArrayOutputStream baosErr = new ByteArrayOutputStream();
        final PrintStream err = System.err;
        try {
            System.setErr(new PrintStream(baosErr));

            this.runCommandLine(args.getArgsArray());

            final String readIn = FileUtils.readFileToString(outputTxt.getAbsoluteFile());
            Assert.assertEquals((int)Integer.valueOf(readIn), expected);
            String errString = baosErr.toString();
            Assert.assertFalse(errString.contains("Warning: using GzipCodec, which is not splittable,"),errString);
        } finally {
            System.setErr(err); //put this back in
        }
```

back to @tomwhite - one small fix and then it's good to go

**Comment by tomwhite** [comment]
I added the test you suggested, @akiezun, and verified that it fails against head.

**Comment by akiezun** [comment]
lgtm

**Pull request merged**
