### PR TITLE
Added a force output sites argument to GenotypeGVCFs

### LINKED ISSUE #6239: PR for GenotypeGVCFs and Non-variant Sites?
Hello,

I'd like to see if your team would potentially be willing to accept a PR to add a feature to GenotypeGVCFs.  The general problem is this:

1) When running GenotypeGVCFs, the default is to output variant sites, and this will therefore vary based on the set of samples.  While there is an argument to include every site, calling against every position of the genome takes a very long time.
2) As you know, a VCF file generally only includes variable sites in the current samples.  Therefore, this doesnt differentiate between the situation where all samples have no data and when all samples are wild-type.
3) We want to merge VCFs with data from different cohorts, including WGS and WES.  It's just not practical to call 1000s of samples as one unit through GenotypeGVCFs (we're constantly adding new data and would need to keep re-calling).  When merging these VCFs, we see a problem that is especially acute at sites with relatively rare variants.  If the variant is only present in one or a few input VCFs, the other VCFs frequently lack that site (they are all wild-type).  On merge, this is interpreted as no-data, which can be misleading.  

The best solution I can devise is to force the input VCFs to output at a whitelist of sites, including if all samples are non-variant.  While GenotypeGVCFs can be made to output at every genomic position, outputting everything is a huge leap in computational time.  

I would propose to make a PR to augment GenotypeGVCFs to support an "--always-output-calls-whitelist" argument.  The user can provide a FeatureInput.  If provided, GenotypeGVCFs would output all variable sites (existing behavior), and also output any position spanning the intervals of this file, even if all samples at wild-type.  

I only just started to look at how to implement this - i can some back with a more specific proposal. However, my initial thought is that we need to hook into drivingVariants or LocusWalker.traverse.

Does your team have any thoughts on this, before we spend too much time on it?  Thanks.

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6239.

@ldgauthier @bbimber Here's what I settled on:

* `GenotypeGVCFs` gets a new argument for force-genotyping intervals.  This is parsed exactly like any other interval argument, so the following are all valid:
```
--force-output-intervals 20:45000
--force-output-intervals intervals.interval_list
--force-output-intervals dbsnp.vcf
--force-output-intervals 20:1000-2000 --force-output-intervals 20:3000-4000
```
* Only the sites matter, so if a VCF is given the alleles are ignored.
* If the site is absent in the input gVCF, there is no output.  No data in yields no data out.
* If the site overlaps a record in the input gVCF, there is output, regardless of whether the record is a variant, a REF block, or a spanning deletion.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
As far as I can tell the failures are just Travis acting up.  `GenotypeGVCFsIntegrationTest` passes locally.

**Comment by ldgauthier** [comment]
@davidbenjamin What's the difference between `--force-output-intervals myIntervals.list` and `--include-non-variants -L myIntervals.list`?

**Comment by bbimber** [comment]
@ldgauthier I have not had a chance to check out this code in detail (I'll try to get someone in my lab to do this today); however, I would hope that the difference is that --force-output-intervals would output at those intervals (whether variant or not) AND include any additional variant sites.  The latter, --include-non-variants and -L would only output the intervals from -L.

**Comment by ldgauthier** [comment]
Yes, thank you for jogging my memory @bbimber.  @davidbenjamin adding something to that extend in the BadArgumentException message would be helpful.

**Comment by davidbenjamin** [comment]
@ldgauthier I wrote a detailed error message.  Anything else?

**Comment by bbimber** [comment]
@davidbenjamin Hello, we started using this feature more seriously and have a question.  the output from GenotypeGVCFs with --force-output-sites seems to include sites with <NON_REF> as the ALT allele.  Is this expected?  I am guessing that these sites used to be filtered (no passing evidence of variation), and the point of this feature is the include sites based on whitelist?

The problem is that some downstream tools dont know what to do with this.  There is probably some subtlety here, but I would think either a given sample has callable variation, it is REF, or it is no-call?  Is <NON_REF> in the output by design?

**Comment by davidbenjamin** [comment]
@bbimber Do I understand correctly that your PR #6406 resolves the issue you found?

**Comment by bbimber** [comment]
yes, it seems to.  it seems this was a simple bug where GenotypeGVCFsEngine.removeNonRefAlleles() wasnt working as intended for multi-allelic sites; however, I'm not sure I understand the entire genotyping process well enough to be certain on this.  we can iterate on #6406

**Pull request merged**
