### PR TITLE
Upgraded Funcotator.wdl to WDL 1.0

### PR DESCRIPTION
**Pull request by tlangs**
Upgraded the Funcotator WDL to WDL 1.0 and implemented new features:
* Automatic disk size calculation
* More readable default parameter settings
* Use of WDL 1.0 features such as defaults and true/false operators
* Using GATK to pull the default datasource rather than wget

### CODE REVIEW

**Comment by lbergelson** [comment]
@jonn-smith Looks like one for you.

**Comment by jonn-smith** [comment]
@tlangs Sorry for the delay in getting to this one.  Any chance you can rebase on top of the latest WDL?  I had to make some updates in the interim.

I haven't seen a lot of this new WDL syntax, but it looks nice.  Do you know offhand which versions of cromwell support it?

**Comment by droazen** [comment]
@tlangs What's the status of this PR?

**Comment by tlangs** [comment]
We've continued to make adjustments to the Funcotator WDL in our own repo, so we should probably close this and make a new PR when the Annotation/Filtration effort is finished.

**Comment by droazen** [comment]
Ok, closing as requested.

**Pull request closed without merging**
