### PR TITLE
fix a bug where SelectVariants takes forever on many-allelic somatic samples

### LINKED ISSUE #6254: SelectVariant raise  OutOfMemoryError
### Affected tool(s) or class(es)

The Genome Analysis Toolkit (GATK) v4.0.7.0

### Description 

I ran the command line below and get an oom error. I've  got the same error when i set the heap memory larger using the param "--java-option Xmx24g" . This procedure only crashed when I tried to select INDEL. I've uploaded the vcf file for you to test.

command line:
```shell
disk/juntong/software/gatk-4.0.7.0/gatk SelectVariants -V /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz -O /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gatk.somatic.indel.vcf.gz -select-type INDEL
```

log:
```
Using GATK jar /disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar SelectVariants -V /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz -O /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gatk.somatic.indel.vcf.gz -select-type INDEL
05:06:54.800 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
05:06:55.409 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.409 INFO  SelectVariants - The Genome Analysis Toolkit (GATK) v4.0.7.0
05:06:55.409 INFO  SelectVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
05:06:55.410 INFO  SelectVariants - Executing as juntong@train1 on Linux v3.10.0-1062.1.1.el7.x86_64 amd64
05:06:55.410 INFO  SelectVariants - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_222-b10
05:06:55.410 INFO  SelectVariants - Start Date/Time: November 6, 2019 5:06:54 AM EST
05:06:55.410 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.410 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.411 INFO  SelectVariants - HTSJDK Version: 2.16.0
05:06:55.411 INFO  SelectVariants - Picard Version: 2.18.7
05:06:55.411 INFO  SelectVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
05:06:55.411 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
05:06:55.412 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
05:06:55.412 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
05:06:55.412 INFO  SelectVariants - Deflater: IntelDeflater
05:06:55.412 INFO  SelectVariants - Inflater: IntelInflater
05:06:55.412 INFO  SelectVariants - GCS max retries/reopens: 20
05:06:55.412 INFO  SelectVariants - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
05:06:55.412 INFO  SelectVariants - Initializing engine
05:06:55.796 INFO  FeatureManager - Using codec VCFCodec to read file file:///disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz
05:06:55.962 INFO  SelectVariants - Done initializing engine
05:06:56.099 INFO  ProgressMeter - Starting traversal
05:06:56.099 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
06:39:06.894 INFO  SelectVariants - Shutting down engine
[November 6, 2019 6:39:06 AM EST] org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants done. Elapsed time: 92.20 minutes.
Runtime.totalMemory()=29215424512
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:265)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
        at java.util.ArrayList.add(ArrayList.java:462)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:392)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculateAnyploidPLcache(GenotypeLikelihoods.java:410)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.initializeAnyploidPLIndexToAlleleIndices(GenotypeLikelihoods.java:518)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.initalizeAlleleAnyploidIndicesCache(SelectVariants.java:629)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.apply(SelectVariants.java:563)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:151)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$68/529766927.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
```

#### Steps to reproduce
[vcf_and_index.zip](https://github.com/broadinstitute/gatk/files/3818610/vcf_and_index.zip)

### LINKED ISSUE #6291: SelectVariants hangs while selecting INDEL type
I think it is a BUG, so I report it here.

I am dealing with a vcf of 748k to seprate INDEL type. But it is hanging for two days... 

```
~/gatktools/gatk-4.1.3.0/gatk SelectVariants \
-R ~/hg19/gatk_bundle/ucsc.hg19.fasta \
-select-type INDEL --variant CS19005_mutect2_filter.vcf.txt \
-O MCS19005_indel.vcf --tmp-dir tmp3
```

[CS19005_mutect2.filtered.vcf.txt](https://github.com/broadinstitute/gatk/files/3899649/CS19005_mutect2.filtered.vcf.txt)
 
Xiucz

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6291.  Closes #6254.

@takutosato The idea here is to only fill an expensive cache of all the different PL indices if the variant has PLs (ie is from HC and not M2).

### CODE REVIEW

**Comment by john-alexander** [comment]
Hi I seem to have this issue on 
gatk/4.0.3.0 and gatk/4.1.4.1. Which version includes the fix?

**Comment by fleharty** [comment]
It was fixed in 4.1.5.0.
You can find the notes in:
https://github.com/broadinstitute/gatk/releases

**Comment by john-alexander** [comment]
Thank you very much, will try this!

**Comment by john-alexander** [comment]
Also Mark, as you would appreciate that I've have fallen on this step after having processed everything else until SelectVariants using GATK v4.0.3,  is it okay to run GATK v4.1.5.0 from selectVariants onwards?

**Comment by lbergelson** [comment]
There are a few other performance fixes for SelectVariants coming in the next release of GATK as well.  We discovered a number of really pathologically cases that we are fixing bu haven't released yet.

**Comment by fleharty** [comment]
@john-alexander 
I prefer to run my workflows in a way that I use the same version of GATK for all tasks and samples.  I realize that isn't always possible, because reprocessing samples with a newer version of GATK may be prohibitively expensive.

There should be no fundamental incompatibility though with using SelectVariants from a more recent version of GATK on data generated from an earlier version of GATK.  So it should work.

If you are going to use a more recent version, I would advocate using the most recent version, no need to use v4.1.5.0 unless you have a very specific reason for thinking something won't work in later versions.

**Comment by john-alexander** [comment]
That is indeed true and helpful - thank you again for the prompt responses!

**Comment by john-alexander** [comment]
Hi,

I managed to run the latest gatk (_SelectVariants_) on our data but ran into the following error: 

`singularity exec /scratch/DBC/BCRBIOIN/SHARED/software/gatk/gatk-4.1.8.1/gatk_latest.sif gatk --java-options "-Xmx12G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" SelectVariants -R /scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/GRCh38.d1.vd1.fa -V /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.orientation_filtered.vcf.gz --exclude-filtered -O /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.passed.vcf.gz

[######@dav002(davros) exec]$ singularity exec /scratch/DBC/BCRBIOIN/SHARED/software/gatk/gatk-4.1.8.1/gatk_latest.sif gatk --java-options "-Xmx12G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" SelectVariants -R /scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/GRCh38.d1.vd1.fa -V /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.orientation_filtered.vcf.gz --exclude-filtered -O /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.passed.vcf.gz
Using GATK jar /gatk/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx12G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -jar /gatk/gatk-package-4.1.8.1-local.jar SelectVariants -R /scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/GRCh38.d1.vd1.fa -V /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.orientation_filtered.vcf.gz --exclude-filtered -O /scratch/DBC/BCRBIOIN/SHARED/analysis/######/######/data/wgs/data/mutect2//tumour_samples/ML13_Ab/ML13_Ab.passed.vcf.gz
10:52:40.838 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Sep 02, 2020 10:52:41 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
10:52:41.263 INFO  SelectVariants - ------------------------------------------------------------
10:52:41.263 INFO  SelectVariants - The Genome Analysis Toolkit (GATK) v4.1.8.1
10:52:41.264 INFO  SelectVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
10:52:41.264 INFO  SelectVariants - Executing as ######@dav002.prv.davros.compute.estate on Linux v3.10.0-327.3.1.el7.x86_64 amd64
10:52:41.264 INFO  SelectVariants - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
10:52:41.265 INFO  SelectVariants - Start Date/Time: September 2, 2020 10:52:40 AM GMT
10:52:41.265 INFO  SelectVariants - ------------------------------------------------------------
10:52:41.265 INFO  SelectVariants - ------------------------------------------------------------
10:52:41.266 INFO  SelectVariants - HTSJDK Version: 2.23.0
10:52:41.266 INFO  SelectVariants - Picard Version: 2.22.8
10:52:41.266 INFO  SelectVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:52:41.266 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:52:41.267 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:52:41.267 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:52:41.267 INFO  SelectVariants - Deflater: IntelDeflater
10:52:41.267 INFO  SelectVariants - Inflater: IntelInflater
10:52:41.267 INFO  SelectVariants - GCS max retries/reopens: 20
10:52:41.267 INFO  SelectVariants - Requester pays: disabled
10:52:41.267 INFO  SelectVariants - Initializing engine
10:52:41.269 INFO  SelectVariants - Shutting down engine
[September 2, 2020 10:52:41 AM GMT] org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2076049408
***********************************************************************

**A USER ERROR has occurred: The specified fasta file (file:///scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/GRCh38.d1.vd1.fa) does not exist.**

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException$MissingReference: The specified fasta file (file:///scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/GRCh38.d1.vd1.fa) does not exist.
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.checkFastaPath(CachingIndexedFastaSequenceFile.java:173)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.<init>(CachingIndexedFastaSequenceFile.java:143)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.<init>(CachingIndexedFastaSequenceFile.java:125)
	at `org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.<init>(CachingIndexedFastaSequenceFile.java:110)`
	at org.broadinstitute.hellbender.engine.ReferenceFileSource.<init>(ReferenceFileSource.java:35)
	at org.broadinstitute.hellbender.engine.ReferenceDataSource.of(ReferenceDataSource.java:27)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeReference(GATKTool.java:435)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:705)
	at org.broadinstitute.hellbender.engine.VariantWalker.onStartup(VariantWalker.java:45)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)`

**Comment by lbergelson** [comment]
@john-alexander Just to be sure, you've checked that file is accessible to singularity?

**Comment by john-alexander** [comment]
Sorry this was my mistake (pretty new to Singularity)!

Fix involved mounting the drive
`singularity exec -B /scratch/DBC/BCRBIOIN/SHARED/genomes/homo_sapiens/GRCh38/dna/:/data /scratch/DBC/BCRBIOIN/SHARED/software/gatk/gatk-4.1.8.1/gatk_latest.sif gatk --java-options "-Xmx12G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" SelectVariants -R /data/GRCh38.d1.vd1.fa -V ML13_Ab.orientation_filtered.vcf.gz --exclude-filtered -O ML13_Ab.passed.vcf.gz`

Also, I just noticed the binary file produced by gatk which works just fine!

Thanks

**Pull request merged**
