### PR TITLE
updating to newer htsjdk snapshot

### PR DESCRIPTION
**Pull request by lbergelson**
updating to a new htsjdk snapshot and updating our VariantContextWriters to compile

test may fail on this....

### CODE REVIEW

**Comment by lbergelson** [comment]
@jean-philippe-martin We're seeing the same errors here as in yours pr.  So it's something in the htsjdk update...

**Comment by cmnbroad** [comment]
Since this is happening at the intersection of CRAM and indexing, I looked into it a bit. It can be readily reproduced if the failing test is run through gradle, but not from IntelliJ, which turns out to be because when it runs through gradle, its using asyncIO for BAM writing, but when run from IntelliJ its using sync io.

I'm not sure why this issue is showing up now, but in the cases that fail, the async writer thread is being interrupted by [this code](https://github.com/samtools/htsjdk/blob/912c28bec415c430b43515652ccaf13222b07e7b/src/main/java/htsjdk/samtools/util/AbstractAsyncWriter.java#L75) which is called from the main thread when the PrintReads closeTool method closes the writer (I added a trace statement to verify this). When I run in IntelliJ and force async io to be used, the interrupt call still happens, but there is no test failure.

**Comment by cmnbroad** [comment]
One short term option would be to turn of async writing until we figure out the right fix.

**Comment by lbergelson** [comment]
The regression was introduced in https://github.com/samtools/htsjdk/commit/1ade6c921628e540f1cab0dfadfbdc536f702d73

**Comment by lbergelson** [comment]
the htsjdk regression was fixed in https://github.com/samtools/htsjdk/pull/992

**Comment by lbergelson** [comment]
@jean-philippe-martin I've updated the htsjdk snapshot, you should be unblocked after a rebase.

**Comment by jean-philippe-martin** [comment]
Thank you very much @lbergelson !

**Pull request merged**
