### PR TITLE
--disableAllReadFilters should allow selective read filter enabling

### PR DESCRIPTION
**Pull request by magicDGS**
Solves #2361.

## EDITED:
Solves also #2363

### CODE REVIEW

**Comment by magicDGS** [comment]
Sorry for the confusion, @droazen. I was also thinking that you were commenting in this one. I will do the changes that you told me soon, but I didn't want to change an argument name without asking first.

**Comment by magicDGS** [comment]
Some changes after the comments from @droazen (in commit #2360):
* Change the argument name from `--disableAllReadFilters` to `--disableToolDefaultReadFilters`
* Make `--disableToolDefaultReadFilters` mutex w.r.t. `--disableReadFilter`
* As pointed out in a different PR (#2355), make all the plugin arguments common.
* Make `isDisabled()` and `getAllInstances()` honor the `--disableToolDefaultReadFilters` argument (solves #2363)

I think that this makes more sense than disable absolutely all the read filters, including the ones provided by the user. The cases where this is more useful are:
- Process the data without filters: provide just `--disableToolDefaultReadFilters`
- Process the data without default filters and add any other: provide `--disableToolDefaultReadFilters` and `--readFilter` with the rest of filters
- Process the data with the default filters and include more: as in the previous behaviour, provide `--readFilter` with the rest of filters
- Process the data with some default filters but change the order: provide `--disableToolDefaultReadFilters` and the list of filters in the new order. 

Can you have a look to this one, @cmnbroad and/or @droazen?

**Comment by cmnbroad** [comment]
@magicDGS Thanks for finding and fixing these. It looks like this is on the right track, but a couple of requests before I review the code in detail:

- I find it much easier to review PRs that have a single initial commit, and then one additional commit per round of review (especially since I often pull the branch into the IDE to inspect code, etc.). I realize there are times when you may want to keep some things separate, but generally one commit per round is easier. 
- Also, its easier to keep each PR independent and not duplicate changes (i.e., there two PRs now that have the same common attribute changes that I asked you to make). Again, there may be exceptions, but generally its easier to minimize duplication.

Can you squash this down to one commit, and then I can review ? Also please see my comments in https://github.com/broadinstitute/gatk/issues/2362, since they affect these changes. Thanks!

**Comment by magicDGS** [comment]
I squash my commits into one, and rebase into the latest master (to be sure that the branch does not have conflicts). Here I'm not adding any method as in #2362, and it is different from the commit that have the change in the argument names (this does not include any ArgumentCollection).

Sorry for the inconvenience of opening too many PRs at the same time.

**Comment by magicDGS** [comment]
Closing. I will open a PR between today and tomorrow with all the workaround for this plugin (before the change in Barclay). We can discuss in the new one the details in a better way.

**Pull request closed without merging**
