### PR TITLE
Extract the revision 1 / "full" filter tables only [VS-1409]

### PR DESCRIPTION
**Pull request by mcovarr**
What appears to be a successful run [here](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Echo%20Callset%20v2/job_history/0e501a3f-3cb1-4bd0-b418-0c4160f0caa2) (requires PMI ops auth).

### CODE REVIEW

**Comment by rsasch** [comment]
why would we want to commit this?

**Comment by mcovarr** [comment]
> why would we want to commit this?

I don't think we do, I was just looking for sanity checks that what I ran was correct.

**Review by gbggrant — APPROVED** [review]
LGTM I guess.
But again - this isn't being merged to EchoCallset, just run off of this branch?

**Comment by mcovarr** [comment]
> But again - this isn't being merged to EchoCallset, just run off of this branch?

Yes that's right, this is the branch I ran the full / rev1 filter extract with. I don't think this should be merged to EchoCallset (not that being on EchoCallset is any guarantee that code will make it back to ah_var_store, but still).

**Review by RoriCremer — APPROVED** [review]
lol gross, but we'll allow it

**Pull request closed without merging**
