### PR TITLE
Added Funcotator excluded fields option explicitly to the M2 WDL.

### LINKED ISSUE #5141: Funcotator - update WDL to include exclude annotations
### Tool(s) or class(es) involved
_Funcotator_

### Description
When the argument to exclude a set of annotations in output is implemented, this must be added as an option in the Funcotator/M2 `WDL`.

### PR DESCRIPTION
**Pull request by LeeTL1220**
- M2 WDL has explicit optional parameter for a list of fields that should be excluded from the output.
- Both M2 WDL files are updated.

Manually tested mutect2.wdl on local backend.

Closes #5141

### CODE REVIEW

**Comment by LeeTL1220** [comment]
I left the unsupported funcotator.wdl alone, minus a doc change to show how to specify `--exclude-field`

**Comment by LeeTL1220** [comment]
@jonn-smith I thought we had agreed (offline) that `funcotator.wdl` could be left alone for this PR.

**Comment by jonn-smith** [comment]
Huh.  I must have completely forgotten about that.

That's fine, then.  

Can you add another issue to bring `funcotator.wdl` up to date?

**Comment by LeeTL1220** [comment]
Issue added

**Pull request merged**
