### PR TITLE
Free up space on github actions runners for all jobs.

### PR DESCRIPTION
**Pull request by cmnbroad**
Add a github action to free up runner space for all jobs.

### CODE REVIEW

**Comment by lbergelson** [comment]
@cmnbroad If you want to make it an action you could take a look at the .github/actions directory.  We have two actions defined there.  Then they can be invokes by their relative path.  Here is an example: 

```
   - uses: ./.github/actions/install-cromwell
        with:
          CROMWELL_VERSION: ${{ env.CROMWELL_VERSION }}
```

**Comment by lbergelson** [comment]
Sorry, I made it harder...

**Comment by cmnbroad** [comment]
@lbergelson Its all good - this is definitely better.

**Comment by lbergelson** [comment]
Actions: shell scripts but the long way around.

**Review by lbergelson — APPROVED** [review]
Looks Github To Me 👍

**Comment by cmnbroad** [comment]
Thanks for the tip, and the review @lbergelson.

**Pull request merged**
