### PR TITLE
Ah [VS-565] output intervals and sample list

### PR DESCRIPTION
**Pull request by koncheto-broad**
This PR does most of the work for VS-565. It exposes the interval list and the sample list to whole way up the nested WDLs to GvsJointVariantCallng.wdl

Two minor things of note:
1. sample_name_list is a File option and not a File because it's only computed inside of a branch of GvsExtractCallset where control_samples is false.  If there is other behavior we want in the condition where it isn't computed, just let me know.  This isn't an issue when it's run inside of GvsJointVariantCalling for the beta workflow though, and making it work there was the ultimate purpose of the ticket.

2. This PR does not fully complete the ticket.  It will also require changes to the actual beta work space to add the necessary columns to the data table sample_set and change the outputs for the GvsJointVariantCalling workflow to map the new outputs to those columns.  I have made these changes and test thems in my copy of the beta workflow, and can make the required changes in the one in gvs-prod once this PR is verified and merged.

### CODE REVIEW

**Comment by koncheto-broad** [comment]
Sure thing! Here's the last successful run:
https://app.terra.bio/#workspaces/gvs-dev/Genomic_Variant_Store_Beta%20AH%20copy/job_history/b3b3e620-bbcc-44af-a445-f41a9e874e55

You can also click over to the data tab and see the new columns for output_vcf_interval_files and sample_name_list.  In this workspace, I made the changes necessary and directed the outputs to those spots

**Comment by mcovarr** [comment]
#protip if you use include a JIRA-formatted ticket id in the PR title (e.g. VS-565), JIRA will automatically link your PR from the ticket.

**Review by mcovarr — APPROVED** [review]
LGTM!

**Review by rsasch — APPROVED** [review]
TIL about how to add outputs back into the Terra Data model!

**Comment by rsasch** [comment]
Sorry, only thought of this after giving my 👍🏻 ; do we want to update the documentation somewhere (e.g. https://github.com/broadinstitute/gatk/blob/ah_vs_565_output_intervals_and_sample_list/scripts/variantstore/beta_docs/run-your-own-samples.md) to let users know where to find these outputs?

**Comment by koncheto-broad** [comment]
That's a good point--the documentation should be updated.  I think it's safe to do so here before I updated actual workspace itself, although technically it has the potential to create a small window in which the documentation talks about features that are not there.  I'll update the ticket in Jira to explicitly mention updating the documentation as well, as it should be among the AC.

**Comment by koncheto-broad** [comment]
I updated the documentation for the beta document and added it to this PR as well

**Pull request merged**
