### PR TITLE
archive 3 tools and related tests

### PR DESCRIPTION
**Pull request by sooheelee**
Ongoing conversation from <https://github.com/broadinstitute/gatk-protected/pull/1130> can now continue in this merged repo.

So far, @vdauwera @droazen and @samuelklee have agreed to delete the code that was requested to be archived in favor of using git versioning as the archive method with these stipulations from Geraldine:

- the PR and commit message specify whether there is a replacement for each of the tools. 
- should be a deprecation message so that if I try to run one of these tools in a newer version, I get a helpful error message that tells me the tool was removed and by what it was replaced if applicable. See GATK3 for how we implemented this previously. This should be done for all tools that we remove, regardless of whether they were purely internal or experimental. It's only a one line addition per tool and it can potentially save us a lot of headaches later down the road (even just internally).

Currently, this PR is the original PR where I placed the to-be-archived code in an archive folder. 

### I have yet to make additional changes so as to follow the above.

### CODE REVIEW

**Comment by sooheelee** [comment]
Tools are:

- DetectCoverageDropout
- DecomposeSingularValues
- CalculatePulldownPhasePosteriors

Nine related docs are:

- CalculatePulldownPhasePosteriors.java			
- CoverageDropoutDetectorTest.java			
- DecomposeSingularValuesIntegrationTest.java
- CalculatePulldownPhasePosteriorsIntegrationTest.java	
- CoverageDropoutResult.java				
- DetectCoverageDropout.java
- CoverageDropoutDetector.java				
- DecomposeSingularValues.java				
- DetectCoverageDropoutIntegrationTest.java

**Comment by sooheelee** [comment]
@samuelklee, are other tools that replace what these tools do? 
@vdauwera, can you point me to an example deprecated tool for gatk3 please?

**Comment by droazen** [comment]
@sooheelee It looks like this PR wasn't ported correctly from the original at https://github.com/broadinstitute/gatk-protected/pull/1130 -- you've lost one of the two commits in the original branch. Step 1 of the migration instructions (https://github.com/broadinstitute/gatk/wiki/Migrating-branches-from-gatk-protected-to-gatk) is to squash your protected branch down to a single commit, which I think wasn't done correctly here.

**Comment by sooheelee** [comment]
I just cherry-picked the second commit onto this same branch. I hope that's okay.

**Comment by sooheelee** [comment]
Ok, since I haven't heard any more comments from folks, it appears we will remove these documents from the repo completely.

**Comment by sooheelee** [comment]
I've made a new PR at https://github.com/broadinstitute/gatk/pull/3033

**Pull request closed without merging**
