### PR TITLE
add GATK to system JAVAPATH

### PR DESCRIPTION
**Pull request by mr-c**
This makes the Docker container more interoperable with other GATK containers that might not install to /gatk

### CODE REVIEW

**Comment by lbergelson** [comment]
@mr-c I'm sorry this PR was forgotten about.  Could you explain what it does? None of us are familiar with the `JAVAPATH` environment variable and googling didn't reveal anything useful.

**Comment by mr-c** [comment]
@lbergelson Thanks for the catch, I mean `CLASSPATH`

**Comment by lbergelson** [comment]
@mr-c Could you make this append to the classpath instead of overwriting it?

**Comment by mr-c** [comment]
@lbergelson Sure, done

**Pull request merged**
