### PR TITLE
Moved tool to gatk-protected

### PR DESCRIPTION
**Pull request by davidbenjamin**
* moved `CalculateTargetCoverage` to gatk-protected in order to make it aware of `Target` and the associated table reader.  That way it can input the standard target table file used in the rest of gatk-protected.
* Deleted `TargetCollectionUtils` as all its methods are obviated by a parallel PR in gatk-protected.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@LeeTL1220 This and the other PR are needed to get the QScripts with GC working.

**Comment by LeeTL1220** [comment]
@davidbenjamin We need to file an issue to move these back into GATK public.

**Comment by LeeTL1220** [comment]
@davidbenjamin This pull request looks okay, but you will need to coordinate a release with @droazen or @lbergelson , since this is not a typical case.

**Comment by davidbenjamin** [comment]
@LeeTL1220 I made a snapshot and switched build.gradle in gatk-protected accordingly in the companion PR.  I have @lbergelson's permission to move this CLI to proitected, with the understanding that we should later try to move it back to gatk-public along with all the supporting `Target` etc classes.

**Pull request merged**
