### PR TITLE
Re-packaging SV classes (#2698)

### PR DESCRIPTION
**Pull request by SHuang-Broad**
Solves #2698.
Three commits, dealing with different problems.
A test failed because of the repackaging but was solved by regenerating the expected file.

### CODE REVIEW

**Comment by SHuang-Broad** [comment]
@cwhelan I know this is being held off for making other changes living on other branches easy. Should we temporarily close this PR and re-open after the public-protected merge, just to make the life of the Engine Team easier?

**Comment by cwhelan** [comment]
yes, let's do that, thanks.

Chris

**Comment by SHuang-Broad** [comment]
Temporarily closing and re-open after Beta release.

**Comment by SHuang-Broad** [comment]
Assigning myself to re-open.

**Comment by SHuang-Broad** [comment]
Re-opened after the merge and Ted's two PR's are in.

**Pull request closed without merging**
