### PR TITLE
Ported Picard tool UpdateVcfSequenceDictionary

### PR DESCRIPTION
**Pull request by magicDGS**
Solves #2222

### CODE REVIEW

**Comment by magicDGS** [comment]
You are assigned to the issue, @cmnbroad. Can you review, please? Thanks a lot!

**Comment by cmnbroad** [comment]
@magicDGS Thanks for doing this, but I've already [implemented](https://github.com/broadinstitute/gatk/commit/8106d95cf68e24983f1d0c31f041b4cae9f75f51) a native GATK version of this, rather than a port of the Picard tool - I just haven't quite finished the tests.

**Comment by magicDGS** [comment]
But if your implementation is a `VariantWalker` and #2223 is implemented, this will class. By the way, I don't know if there is any plan to include all the tools from Picard, but it seems that the behaviour will be replicated if so, no?

Thanks anyway for the feedback, close the PR in case you think that it is not necessary.

**Comment by cmnbroad** [comment]
Yeah - not sure about the duplication (I didn't even know this Picard tool existed). @droazen whats your preference ?

**Comment by droazen** [comment]
I'd tend to prefer a native GATK tool, but let's see both versions as pull requests and pick the best/most functional one. A key requirement in the ticket is to support many different sources of sequence dictionaries: a fasta reference, a bam, a .dict file, another VCF that already has a dictionary, etc.

**Comment by droazen** [comment]
@cmnbroad Could you review this branch, and give a summary of how this version compares to the one in https://github.com/broadinstitute/gatk/pull/2234? Is one implementation more functional than the other?

**Comment by magicDGS** [comment]
I had a look to the other branch, @droazen, and I think that it is more functional than this one:

* Check if the input already have a sequence dictionary, and only updates if  `--replace` is provided. The version in this PR just overrides the dictionary.
* Check if all the variants agree with the new sequence dictionary, throwing an error if the contig is not present or the variant falls outside the chromosome range. This version does not account at all for that.
* It is a `VariantWalker`, and thus the code is simplest. But the pitfall of this is that if #2223 is implemented, that class will require a dictionary for the input as a `GATKTool`. I'm not sure how that is going to be done, but I guess that it will introduce problems in the class implemented by @cmnbroad.

I think that the other version is more complete and I like it more because it is more concern about putative problems.

**Comment by cmnbroad** [comment]
I agree with everything @magicDGS said. In general, the native GATK tool benefits from all of the automatic framework management and I/O support (like honoring md5, lenient args, etc.). #2234 also has the validation checking mentioned, and has more tests. (It is true that when #2223 goes in, we'll have to override the default sequence dictionary validation behavior, maybe via disableSequenceDictionaryValidation).

So I think we should take the native one, but if we do choose to keep this one for any reason, then I'll still want to do a line-by-line CR before we merge.

**Comment by lbergelson** [comment]
@magicDGS @cmnbroad Going to close this one in favor of #2234.

**Pull request closed without merging**
