### PR TITLE
adding timeout protection

### PR DESCRIPTION
**Pull request by lbergelson**
this should stop the timeout errors

### CODE REVIEW

**Comment by droazen** [comment]
We really need a fix for this -- travis still timing out today :(

**Comment by lbergelson** [comment]
It's having a dumb bash quoting error that I don't understand.

**Comment by lbergelson** [comment]
it was a typo, should be fixed now.

**Comment by lbergelson** [comment]
I suspect that this is the culprit of the failures:
```
readsSinkTest[3](/home/travis/build/broadinstitute/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam, ReadsSparkSinkUnitTest4, .bam)	4m19.05s	passed`
```

**Comment by lbergelson** [comment]
@droazen Ok to merge now?

**Pull request merged**
