### PR TITLE
Changes for issue #2713, #2714 and #2715

### PR DESCRIPTION
**Pull request by kdatta**
Added validateSampleNameMap command line parameter
  Added a unit test
  Updated genomicsdb version to 0.6.3

### CODE REVIEW

**Comment by kdatta** [comment]
@lbergelson tagged

**Comment by droazen** [comment]
@kdatta Before we review, can you tell us whether the new genomicsdb version in this branch includes the change in https://github.com/Intel-HLS/GenomicsDB/pull/115?

**Comment by kdatta** [comment]
Not yet. haven't released genomicsdb version 0.6.3-proto-3.0.0-beta-1. Will let you know once its done.

**Comment by droazen** [comment]
@kdatta No worries -- I think we need one more review pass on that GenomicsDB PR anyway before we can merge it.

**Comment by kdatta** [comment]
that's what I'm waiting for

**Comment by kdatta** [comment]
is something wrong with Travis today?

**Comment by kdatta** [comment]
My builds are queued, but not started for more than 4 hours

**Comment by lbergelson** [comment]
Hmn, we could be seeing quota issues.  We just dramatically increased the size of our build matrix and there's a ton of work going on today.  It's hard to tell because there's no way to view the queue...

**Comment by lbergelson** [comment]
Apparently there's a travis wide outage.  https://www.traviscistatus.com/incidents/bnt2wtxpgs39

**Comment by kdatta** [comment]
@droazen, I cannot restart a build in Travis. Think I need write permission for that!

**Comment by droazen** [comment]
@kdatta I've restarted it for you.

**Comment by lbergelson** [comment]
This update of genomicsDB includes the option to not validate the sampleMapFile against the actual headers.  Choosing to not validate allows us to save time at the start by not having to open each file on the initial header construction  when using --`sampleMapFile`.  closes #2713, closes #2714,  and closes #2715.

It also includes an update to have GenomicsDB capture RSId's by default, (closes  #2636) which should make diffs easier on our end at a slight cost of storage size.  If that's an issue we may need to revisit the default.

**Comment by lbergelson** [comment]
closed by #2733

**Pull request merged**
