### PR TITLE
Bait count bias correction for TargetCoverageSexGenotyper (duplicate)

### PR DESCRIPTION
**Pull request by mbabadi**
- improved baits count annotator ("lazy" post processing)
- included bait counts as a multiplicative bias in TargetCoverageSexGenotypeCalculator
- improved info and warn log messages in TargetCoverageSexGenotyper
- interval exclusion via CLI args for TargetCoverageSexGenotyper
- soft target filtering using masks
- more extensive unit/integration tests for TargetCoverageSexGenotyper
- integration test for annotate targets w/ bait counts
- missing test resource files from gatk-protected repo
- address PR review

### CODE REVIEW

**Comment by mbabadi** [comment]
@droazen @samuelklee this is a duplicate PR, I close the previous one. Travis was behaving strangely on the previous PR (oddly not picking up the correct commit for `continuous-integration/travis-ci/pr` test).

**Comment by samuelklee** [comment]
This was already re-reviewed and OK'ed by me.  Looks like the Travis PR build is still picking up the wrong commit and failing, though

**Comment by mbabadi** [comment]
@lbergelson @droazen I still get strange travis-related errors with this... could you please take a look?

**Comment by lbergelson** [comment]
@mbabadi It looks like you hit a transient git-lfs failure.  I'm not sure what we can do to prevent them but rerunning fixed it.

**Pull request merged**
