### PR TITLE
Set AD and DP to zero if no read coverage

### PR DESCRIPTION
**Pull request by ronlevine**
Implements #2370.

### CODE REVIEW

**Comment by ronlevine** [comment]
@lbergelson Please review.

**Comment by lbergelson** [comment]
@ronlevine In the original gatk3 pr you also updated `DepthPerAlleleBySample`.  Is that not necessary in gatk4?

**Comment by ronlevine** [comment]
It's not necessary to update `DepthPerAlleleBySample`. This is verified in `DepthPerAlleleBySampleUnitTest`.

**Comment by lbergelson** [comment]
@ronlevine 👍

**Pull request merged**
