### PR TITLE
Qual = 0 sites don't count as polymorphic for GVCF mode

### PR DESCRIPTION
**Pull request by davidbenjamin**
@ldgauthier This is for #4614.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
I was assuming I would change the default in the same PR that makes new qual default.

**Comment by ldgauthier** [comment]
Fair point.  I'll try to help remember.

**Comment by davidbenjamin** [comment]
Is this PR good to merge then?

**Comment by ldgauthier** [comment]
:+1:

**Pull request merged**
