### PR TITLE
Doc updates for CollectBaseDistributionByCycleSpark, GetPileupSummaries, Pileup, PileupSpark, CollectInsertSizeMetricsSpark, CollectMultipleMetricsSpark, InsertSizeMetricsCollectorSpark, CompareBaseQualities

### PR DESCRIPTION
**Pull request by mbabadi**

### CODE REVIEW

**Comment by sooheelee** [comment]
Just seeing this @mbabadi. Happy to look through the doc portion. If there are any code changes,  you'll have to conscript an additional reviewer.

**Comment by sooheelee** [comment]
I will make my doc-portion suggestions and program group reassignments to the branch directly, to save us the back and forth @mbabadi

**Comment by mbabadi** [comment]
@sooheelee thanks for the updates. I'll look into the two issues you mentioned.

**Comment by sooheelee** [comment]
@mbabadi you're welcome! 

About those two issues--I learned that with VPN on, Spark tools error locally (thanks to Steve). I turned off my VPN connection and am able to run PileupSpark locally.

One other thing to note for PipeupSpark documentation--the tool will error if the output filename already exists. That is, unlike other GATK tools, it will not overwrite existing file names. Either this unusual behavior should be fixed or mentioned in the tooldoc. I'm testing this with dataproc now.

When running locally, neither CollectBaseDistributionByCycleSpark nor CollectInsertSizeMetricsSpark output the PDF file. So this seems a bug and I'll put in an issue ticket if there isn't one already.

**Comment by mbabadi** [comment]
@sooheelee build was failing due to the removal of `DiagnosticsAndQCProgramGroup`. Changes to `CoverageAnalysisProgramGroup` and rebased. Waiting for travis. Good to merge?

**Comment by sooheelee** [comment]
@mbabadi you should get confirmation from @droazen for any changes--commits, merges.

**Comment by mbabadi** [comment]
@sooheelee will do, thanks!

**Comment by mbabadi** [comment]
@droazen This is good to go from our end, David. The program group assignments may not some fine tuning though.

**Comment by droazen** [comment]
@mbabadi Could you rebase this branch onto latest master?

**Comment by cmnbroad** [comment]
DiagnosticsAndQCProgramGroup still exists, its just in the picard.cmdline.programgroups package.

**Comment by droazen** [comment]
Rebasing this branch now

**Pull request merged**
