### PR TITLE
Compressed vcf output and Funcotator options in Mutect2 wdl

### LINKED ISSUE #4188: M2 WDL script wishlist
For @davidbenjamin. I've been asked to take the user-perspective and report things I'd want to make our WDL scripts more extensible. So here goes.

screenshot 2018-01-17 13 22 27

## Major wants
- The is_bamout Boolian appears to be hardcoded to `false` in the script. Users need to be able to understand that this option can be changed without ambiguity. So this should become a proper  optional variable. @LeeTL1220 tells me this can be overwritten. However, why leave this as misinterpretable to newbie WDL-scriptors? Especially since `wdltools inputs` doesn't include it as a variable at all in the generated inputs list. Please can we make this a proper optional argument that `wdltools inputs` will generate a variable for.
- [ "${variants_for_contamination}" == *.vcf ] does not allow *.vcf.gz files. It should accept either.
- Outputs should allow either .vcf or .vcf.gz compression by user-specification. Alternatively, if we want to keep it simple and hardcode, then the preference is for compressed files. Some of us prefer to save on storage.
- Need to be able to specify optional string args for SplitIntervals. I would like to be able to use the BALANCING_WITHOUT_INTERVAL_SUBDIVISION mode. Furthermore, I'd like for the tool to automatically interpret this mode, when not given an -L intervals list, to not split reference contigs. I.e. a contig is an interval. (Perhaps already the tool behavior?)
- The version of Oncotator is not compatible with GRCh38. Please, can we have an option to switch this out with Funcotator? 

## Minor wants
- The JSON template in the repo should show the optional variables.
- Script calls for a Picard jar. I don't mind specifying this because I like controlling for the Picard version I use. However, users may want to call the Picard version within the GATK jar. I cannot fathom a simple way to allow switching this out in the script, but perhaps something like the gatk_override option could work. The goal would be to call the Picard tool from a Docker. This better enables provenance.

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #4188.

@sooheelee This wraps up the wish list in #4188.

@takutosato Although funcotator is off in the Travis test, I *did* test it locally. Also, I have tested with and without compressed vcf output.  The funcotator command is simply copied from @jonn-smith's funcotator.wdl.  Subworkflows are a pain in Firecloud, which is why I don't `import` it.

### CODE REVIEW

**Comment by samuelklee** [comment]
@davidbenjamin What is the issue with subworkflows?  We import some subworkflows in the CNV WDLs.  I think sub-subworkflows are when things get hairy...

@jonn-smith @LeeTL1220 Let me know at what point we should switch over to Funcotator (or make it an option) in the CNV WDLs as well.  I'd also feel more comfortable if the Funcotator/Oncotator tests actually ran on Travis.

**Comment by davidbenjamin** [comment]
@samuelklee It's quite possible I just plain misunderstood about subworkflows.  There may still be something to be said for making the M2 wdl totally self-contained, but that's a call for Lee and Geraldine.

**Comment by LeeTL1220** [comment]
@davidbenjamin Oncotator runs in the M2 WDL travis tests (last I checked).  It just uses no datasources.  Oncotator is disabled for the CNV WDL travis tests.  I did this because the CNV Oncotator uses a different docker image, which is fairly large.

@davidbenjamin @samuelklee Life is only a little bit easier if the WDL is self-contained.    The sub-...-workflows gets a little hairy for setting optional parameters (particularly runtime parameters).

**Comment by davidbenjamin** [comment]
@LeeTL1220 So what's the verdict -- import the funcotator workflow or make the M2 wdl self-contained with a Funcotator task?  If the former, what do I need to do to un-break M2 in Firecloud?

**Comment by LeeTL1220** [comment]
@davidbenjamin I would make the Funcotator inline in the M2 WDL for now.  As sub-workflows get easier to manage, maybe we re-assess.  I'm punting on CNV since Funcotator does not support CNV yet.

**Comment by davidbenjamin** [comment]
@takutosato Lee's offline verdict was to keep Funcotator inlined in the M2 wdl for now, so this PR can stay as-is.

**Pull request merged**
