### PR TITLE
Update ojAlgo and improve commons-math / ojAlgo integration

### PR DESCRIPTION
**Pull request by apete**
You're using an old version of ojAlgo. I upgraded it for you. There has been improvements to the SVD implementations. (Significant improvements to some users.)

Also added a dependency to ojalgo-commons-math3 which gives you wrapper classes to convert back and forth between ojAlgo and Commons Math matrix classes. You no longer need to copy the resulting matrices.

### CODE REVIEW

**Comment by lbergelson** [comment]
@apete Thanks for the PR!  That's really helpful to update and any svd improvements are definitely something we want. 

It's failing to build though, because it can't locate `ojalgo-extensions-1.0.0`

I get the following error:
```
Build file '/Users/louisb/Workspace/gatk/build.gradle' line: 511

* What went wrong:
A problem occurred evaluating root project 'gatk'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not resolve org.ojalgo:ojalgo-commons-math3:1.0.0.
     Required by:
         project :
      > Could not resolve org.ojalgo:ojalgo-commons-math3:1.0.0.
         > Could not parse POM https://repo1.maven.org/maven2/org/ojalgo/ojalgo-commons-math3/1.0.0/ojalgo-commons-math3-1.0.0.pom
            > Could not find org.ojalgo:ojalgo-extensions:1.0.0.
              Searched in the following locations:
                  https://repo1.maven.org/maven2/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.pom
                  https://repo1.maven.org/maven2/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.jar
                  https://jcenter.bintray.com/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.pom
                  https://jcenter.bintray.com/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.jar
                  https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.pom
                  https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.jar
                  file:/Users/louisb/.m2/repository/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.pom
                  file:/Users/louisb/.m2/repository/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.jar
      > Could not resolve org.ojalgo:ojalgo-commons-math3:1.0.0.
         > Could not parse POM https://jcenter.bintray.com/org/ojalgo/ojalgo-commons-math3/1.0.0/ojalgo-commons-math3-1.0.0.pom
            > Could not find org.ojalgo:ojalgo-extensions:1.0.0.
      > Could not resolve org.ojalgo:ojalgo-commons-math3:1.0.0.
         > Could not parse POM https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/org/ojalgo/ojalgo-commons-math3/1.0.0/ojalgo-commons-math3-1.0.0.pom
            > Could not find org.ojalgo:ojalgo-extensions:1.0.0.
```

If I look on [maven central](http://search.maven.org/#search%7Cga%7C1%7Cojalgo) I see math3, but I don't see ojalgo-extensions.  Is it possible that artifact hasn't been published to maven central yet?

**Comment by apete** [comment]
Yes, I forgot to publish the parent pom - that's all ojalgo-extensions is. I'm looking into how to fix this.

**Comment by apete** [comment]
I believe it's fixed now. Just need to wait for it to become available.

**Comment by lbergelson** [comment]
@apete Thanks a lot.  I will rerun the tests in a bit then.

**Comment by apete** [comment]
Should work now:

...
Download https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/com/google/cloud/google-cloud-nio/0.20.4-alpha-SNAPSHOT/google-cloud-nio-0.20.4-alpha-20171031.194208-5.pom
Download https://repo1.maven.org/maven2/org/ojalgo/ojalgo-extensions/1.0.0/ojalgo-extensions-1.0.0.pom
Download https://repo1.maven.org/maven2/com/intel/gkl/gkl/0.8.2/gkl-0.8.2.pom
...

**Comment by lbergelson** [comment]
There was a conflict in the gitignore, I think it's fixed now.

**Comment by apete** [comment]
@lbergelson Sorry for all the problems! Apart from the fact that I had forgotten to publish the parent pom, I'm not a gradle user. Had no idea you have to explicitly call 'test' to run (or even compile) the tests.

**Comment by lbergelson** [comment]
@apete Thanks for all the help, sorry it was such an ordeal.  Running the tests locally takes quite a long time, so pushing a PR is really the best way to run them anyway.

**Pull request merged**
