### PR TITLE
backport 1 method from protected and renamed 1 file

### PR DESCRIPTION
**Pull request by akiezun**
@lbergelson can you review and make a snapshot with those? It will allow me to cleanup https://github.com/broadinstitute/gatk-protected/pull/610 and delete 2 more classes from there

### CODE REVIEW

**Comment by droazen** [comment]
(snapshots of master are made automatically)

**Comment by akiezun** [comment]
do they include all the code that we need? (maybe they do now that we've
moved to using gkl)?

**Comment by droazen** [comment]
Yes, they should, since we're no longer building the native libraries from source!

**Comment by lbergelson** [comment]
So the continuous snapshots broke for a mysterious reason.  https://github.com/broadinstitute/gatk/issues/1993

**Comment by akiezun** [comment]
@samuelklee can you review? this is a change you made in protected and i backported here

**Comment by samuelklee** [comment]
:+1:

**Pull request merged**
