### PR TITLE
Allow Spark UI to run during tests by setting the gatk.spark.debug system property

### PR DESCRIPTION
**Pull request by tomwhite**
This it for https://github.com/broadinstitute/gatk/issues/972. By adding `-Dgatk.spark.debug=true` you can run a single Spark test and look at the Spark UI (on http://localhost:4040/) as it runs.

### CODE REVIEW

**Comment by akiezun** [comment]
looks great @tomwhite. Is there a way to keep it visible when the jvm completes?

**Comment by akiezun** [comment]
:+1: merging

**Comment by tomwhite** [comment]
@akiezun It would be nice to have the JVM stay around, but I didn't get it to work when I tried (with a non-daemon background thread). Perhaps someone else knows how to get gradle not to exit?

**Comment by lbergelson** [comment]
I don't know how to accomplish that with gradle.  Is just keeping the test jvm going all we need? Or does the ui shutdown after each test?  We could add an infinitely running "test" in a special test group to If we want to be keep the test jvm open.  Alternatively if we really need to be able to run tests and then view the UI afterwards we could put together something using https://github.com/hammerlab/spree.  It's a minor pain to set up, I had weird ruby packaging problems getting meteor installed, but it solves the problem of "how do we collect spark logs in a usable way".

**Pull request merged**
