### PR TITLE
Revert "use snappy and 512k blocks"

### PR DESCRIPTION
**Pull request by akiezun**
Reverts broadinstitute/gatk#1861

### CODE REVIEW

**Comment by akiezun** [comment]
will merge when tests pass. speak up now if you disagree.

**Comment by droazen** [comment]
Do you have a ticket opened to eventually re-enable this?

**Comment by akiezun** [comment]
now we do #1873

**Comment by droazen** [comment]
@akiezun Have we captured all of the performance suggestions from Intel in github tickets? (I know this was one of them)

**Pull request merged**
