### PR TITLE
extract sample name from input read groups and create an output read …

### PR DESCRIPTION
**Pull request by cwhelan**
…group for the contig alignments

To do downstream stuff like correlate breakpoints in copy number calls that are in VCF format, and perhaps eventually put a genotype column in our output VCF, it would be helpful to keep track of the sample name. This PR tries to help do that by 1) validating that input read groups contain reads from only one sample, 2) extracting the sample name for future use, and 3) putting a constructed read group in our aligned assemblies output file that contains the sample name, and tagging all of the alignment records in that file with the read group id. 

As part of testing this I added an expected aligned contigs file test to `FindBreakpointEvidenceSparkIntegrationTest`.

### CODE REVIEW

**Comment by samuelklee** [comment]
This is something we also want to address in the CNV pipeline soon.  However, we typically need to append sample metadata to TSVs (rather than SAMs) and TableReader/TableWriter currently only allows for comment lines starting with `#`.  Hence, in #2858 we tack on a `#SAMPLE_NAME=...` header, which is quite hacky.  Perhaps we can discuss unifying this sort of thing (along with appending sequence dictionaries when appropriate) across the tools?

**Comment by cwhelan** [comment]
@samuelklee In a perfect world, I think I'd prefer VCF as our interchange format for CNV calls, and there the sample names are nicely baked into the format. I asked @mbabadi about this the other day and he thought that was the direction gCNV would eventually move in. In the case here, we want to infer the sample name from the input BAM file, where it's stored in the RG tags. The aligned assemblies output file I'm talking about here is really a temporary output sort of akin to a HaplotypeCaller bamout, and again there I think it's natural to add a readgroup with the sample name.

**Comment by samuelklee** [comment]
We will certainly output VCFs for our final calls, but we also have useful intermediate file formats that would benefit from having the sample name (and sequence dictionary, if appropriate) attached---for example, our read-count and allelic-count files.  I see no reason that these shouldn't have a header with the appropriate tags generated from the input BAM and be read/written in the Tribble framework.

However, there are a few exceptions in the CNV pipeline for files that not collections of Features but are still associated with a sample, so I think it would be nice to extract out the sample-name related code across the various tools.  This is not only to avoid duplicating effort, but also to standardize how we store this information in our various file formats.

**Comment by cwhelan** [comment]
@samuelklee Ah, I see what you are saying. Maybe something like a `SampleDataTable` in Tribble or something? Sounds like a good idea.

**Pull request merged**
