### PR TITLE
Add a --disableContigOrderingCheck argument to GatherVcfs to disable the comparison of relative contig ordering during a conventional gather

### PR DESCRIPTION
**Pull request by droazen**
With this argument, we still check start positions to make sure they're increasing within a given contig
during a conventional gather, but we don't enforce relative ordering of contigs using the ordering of
the sequence dictionary in the VCF header.

### CODE REVIEW

**Comment by droazen** [comment]
@lbergelson please review. This is a quick-and-dirty temporary fix to work around https://github.com/broadinstitute/gatk/issues/2753, and if we can fix the underlying problem quickly this may not be worth even merging.

**Comment by lbergelson** [comment]
I disapprove of this gross duplication, but since it's running in production I think it's best to merge this thing anyway for now.

**Comment by ronlevine** [comment]
IIRC, this use of this feature was discouraged in GATK3 . Right @vdauwera? Making a new release of  HTSJDK and incorporating it should fix the underlying problem.

**Comment by droazen** [comment]
I want this argument as a fallback for now in case production runs into more trouble with the upcoming callset. Merging in so @lbergelson can incorporate this change in his upcoming patch to `GatherVcfs`

**Pull request merged**
