### PR TITLE
Update to htsjdk 2.8.0

### PR DESCRIPTION
**Pull request by droazen**

### CODE REVIEW

**Comment by droazen** [comment]
Going to merge https://github.com/broadinstitute/gatk/pull/2247 first, then rebase on top of it.

**Comment by droazen** [comment]
@lbergelson please review

**Comment by vdauwera** [comment]
You didn't run into the variant filtration problem we got in gatk3?

**Comment by droazen** [comment]
@vdauwera All tests passed. Can you describe the problem you had in GATK3?

**Comment by ronlevine** [comment]
`--missingValuesInExpressionsShouldEvaluateAsFailing` is not working.

**Comment by droazen** [comment]
@ronlevine I don't see a test covering that argument in GATK4. If you have such a test in GATK3, could you port it to GATK4 (or write a new test if the old one depends on large files in the Broad filesystem)?

**Comment by ronlevine** [comment]
There is GATK3 unit and integration test and could port them.

**Pull request merged**
