### PR TITLE
Move to the latest version of google-cloud-java

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Main motivation: it includes fixes we need for writing to
Google Cloud Storage buckets via NIO.

However this comes with some API changes too so we must agree
on what to do there.

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
It looks like this version sadly doesn't include the [package rename](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1767).

**Comment by jean-philippe-martin** [comment]
A workaround is to comment out the one method that needs it until the next release (no one inside of gatk calls this method). Would that be OK?

**Comment by droazen** [comment]
Which method is that @jean-philippe-martin ?

**Comment by jean-philippe-martin** [comment]
It's `BucketUtils.getAuthenticatedGcs`

**Comment by droazen** [comment]
That method is used in tests, isn't it? 

I'd be ok with commenting it out for now for the sake of getting this merged, provided that you open a ticket to uncomment the method and re-enable the relevant tests once the package rename is available.

**Comment by jean-philippe-martin** [comment]
Yes you're right, it's only used in tests. Adding a ticket for it.

**Comment by jean-philippe-martin** [comment]
@droazen Was that a thumbs up, or would you like to do more checking before I squash and merge?

**Comment by droazen** [comment]
That was not a thumbs up, but this is ----> 👍   merge when ready!

**Pull request merged**
