### PR TITLE
Update numpy\scipy\pymc3 python package 

### LINKED ISSUE #6978: Update numpy\scipy\pymc3 python package
### Tool(s) or class(es) involved

python\gcnvkernel
python\vqsr_cnn

### Description
 want to use the newer numpy 1.19.4, but I found that gatk uses conda-force to install the older numpy 1.17.5, and it is not allowed to upgrade numpy because of scipy version restrictions. And scipy cannot be upgraded because of the version limitation of pymc3.

I think we should use the new version of the software (in the new version, some bugs are fixed, the performance is better), we need to deal with the difficulties and help the software upgrade.

### PR DESCRIPTION
**Pull request by zaneChou1**
fix #6978

### CODE REVIEW

**Comment by samuelklee** [comment]
See https://github.com/broadinstitute/gatk/issues/6978#issuecomment-733001543

**Comment by samuelklee** [comment]
@zaneChou1 are you interested in continuing this work? I have not been able to work on the issue myself just yet. As noted in the the thread linked above, it will require nontrivial changes beyond the updates to package versions you've made here, including changes to the gCNV to account for PyMC3 API updates.

**Review by samuelklee — CHANGES_REQUESTED** [review]
score_breakpoints(intervals_vcf_file, breakpoints, padding=10000)

**Comment by zaneChou1** [comment]
> @zaneChou1 are you interested in continuing this work? I have not been able to work on the issue myself just yet. As noted in the the thread linked above, it will require nontrivial changes beyond the updates to package versions you've made here, including changes to the gCNV to account for PyMC3 API updates.

Yes, I am interested. And I will try to change to the gCNV to account for PyMC3 API updates.

**Comment by samuelklee** [comment]
Obviated by #8094. But thank you for your efforts, @zaneChou1!

**Pull request closed without merging**
