### PR TITLE
*ON HOLD*: Update SharedSequenceMerger.java

### PR DESCRIPTION
**Pull request by githublet**
https://gatkforums.broadinstitute.org/gatk/discussion/11236/a-logical-problem-with-splitcommonsuffices-and-mergecommonsuffices#latest

### CODE REVIEW

**Comment by vruano** [comment]
Please keep this PR on hold until we can clarify what is trying to fix.

**Comment by droazen** [comment]
Before we can accept a change like this, we need a good unit test to illustrate the problem that this patch fixes. The test should fail without the fix, and pass with it.

**Comment by githublet** [comment]
@droazen @vruano 
change code just because in **CommonSuffixSplitter.java** some code like this:
                **for** ( final SeqVertex mid : **toSplit** ) {
                    // create my own copy of the suffix
                    final SeqVertex suffixV = new SeqVertex(**suffixVTemplate.getSequence()**);
                    graph.addVertex(suffixV);
so I think in **SharedSequenceMerger.java**,better merge vertices incomingVertices.size()>1

**Comment by githublet** [comment]
I recode java to c (just haplotypecaller step 2), and will merge CommonSuffixSplitter.java SharedSequenceMerger.java in to one file, 
I'll just add vertex suffixVTemplate(graph.addVertex(suffixVTemplate)),then add in_edge to suffixVTemplate, last do something like this(this is not c code): final SeqVertex newV = new SeqVertex(ArrayUtils.addAll(suffixVTemplate.getSequence(), v.getSequence())).
for some test ,also the algorithm does,after process removePathsNotConnectedToRef(),
MergeTails() does not work!May be we can change MergeTails.java where logic like SharedSequenceMerger.java.

**Comment by droazen** [comment]
Closing this one, since we still don't have a test illustrating the problem, and @vruano doesn't see the problem after considerable back-and-forth on the forum.

**Pull request closed without merging**
