### PR TITLE
fix for bqsr table mismatch

### PR DESCRIPTION
**Pull request by akiezun**
fix for https://github.com/broadinstitute/gatk/issues/1414

@lbergelson please review and confirm that this fixes the problem you saw (remaining diffs are all 0.01)

### CODE REVIEW

**Comment by droazen** [comment]
It's kind of worrisome that this one if statement never got ported to GATK4 (according to git it's never been in our codebase!), and a lot more worrisome that our tests didn't catch it. Do you think that we should add more heavy-duty integration tests for BQSR to our core test suite in travis, or rely on the larger-scale tests to be activated in https://github.com/broadinstitute/gatk/issues/1401 + the official production tie-out?

**Comment by lbergelson** [comment]
@akiezun Seems to have conflict, probably with the always sort branch that I just merged.  Everything else looks good though.  I'm confused why we didn't notice this in our earlier testing.

**Comment by lbergelson** [comment]
Feel free to merge once rebased.

**Comment by akiezun** [comment]
yes, https://github.com/broadinstitute/gatk/issues/1401 will address running large scale tests.

**Pull request merged**
