### PR TITLE
Utils methods to stream Iterable/Iterator

### PR DESCRIPTION
**Pull request by davidbenjamin**
Because calling `StreamSupport.stream(iterable.spliterator(false))` is really ugly.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@SHuang-Broad could you take a look at this?

**Comment by SHuang-Broad** [comment]
Sorry for the late noticing. Will work on it now.

**Comment by SHuang-Broad** [comment]
Looks good to me, except one concern about the use of `0` as the characteristics when streaming iterators (unset all bits in the characteristics of the returned spliterator). What about doing it in the way as suggested by accepted answer [here](http://stackoverflow.com/questions/24511052/)?

**Comment by davidbenjamin** [comment]
@SHuang-Broad done (assuming tests pass).  Is this what you meant?

**Comment by SHuang-Broad** [comment]
Sorry for the confusion, but assuming the iterator is iterating through an ordered container is not safe, I think. What about this:

```java
public static <T> Stream<T> stream(final Iterator<T> iterator) {
    return stream(() -> iterator);
}
```

It is reusing the version working with `Iterable`'s.

**Comment by davidbenjamin** [comment]
@SHuang-Broad done!

**Comment by SHuang-Broad** [comment]
👍

**Pull request merged**
