### PR TITLE
use original qualities in applyBQSR

### LINKED ISSUE #1125: ApplyBQSR ignores useOriginalQualities
in GATK3 useOriginalQualities is an engine level argument. In hellendender, it's only used in BaseRecalibrator and so you can't applyBQSR on originalBase qualities.

@eitanbanks is this an alpha requirement?

### PR DESCRIPTION
**Pull request by akiezun**
fixed #1125

### CODE REVIEW

**Comment by akiezun** [comment]
for @lbergelson

**Comment by davidadamsphd** [comment]
I don't see any issues, just one question: does this only apply to the walker version?

**Comment by akiezun** [comment]
no, because it's in the transformer, it applies to all. 
See the spark test

**Comment by davidadamsphd** [comment]
Gotcha, LGTM.

**Pull request merged**
