### PR TITLE
Release new version of GVS

### PR DESCRIPTION
**Pull request by rsasch**

### CODE REVIEW

**Review by mcovarr — COMMENTED** [review]
Are there more beta-user-visible changes we'd want to document since March? e.g. ploidy, FT header changes, possibly others

**Comment by rsasch** [comment]
> Are there more beta-user-visible changes we'd want to document since March? e.g. ploidy, FT header changes, possibly others

Probably, but those changes might warrant a larger jump in version.

**Comment by kbergin** [comment]
I see now that we have a changelog (didn't look at the code change before commenting). I do think any change that's included in the release should be in the changelog.

**Review by mcovarr — CHANGES_REQUESTED** [review]
I don't have a strong opinion about the version number, but from the discussion on the PR it sounds like we want to document the user facing changes since the last version here.

**Comment by rsasch** [comment]
> I don't have a strong opinion about the version number, but from the discussion on the PR it sounds like we want to document the user facing changes since the last version here.

Happy to incorporate any suggested additional text.

**Comment by kbergin** [comment]
I didn't realize we hadn't been updating the changelog /releasing when we added new features anymore. 

A few other things that happened recently (not sure if they were before or after last release)
- high_CALIBRATION_SENSITIVITY_SNP and high_CALIBRATION_SENSITIVITY_INDEL were moved from the ##FILTER entry in the header to a ##COMMENT. No change to behavior or vcf content outside of header.
- Reduced the number of sharded vcfs coming out of beta workflow for smaller callsets. Documentation on details coming soon.
- Bug fix to correctly handle samples with chromosomes with differing ploidy for DRAGEN 3.7.8 data.

**Comment by mcovarr** [comment]
Yeah we really should be updating the changelog / making releases regularly for user-facing changes...

The three items Kylee lists above were in fact added since the previous release.

**Review by kbergin — APPROVED** [review]

**Review by mcovarr — APPROVED** [review]

**Pull request merged**
