### PR TITLE
Add test illustrating GenotypeGVCFs/forceoutput N issue

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
I need to look into this more - it's not worth trying to review or repro this yet.

**Comment by nalinigans** [comment]
Thanks @bbimber, this will greatly aid me and @mlathara.

**Comment by bbimber** [comment]
@nalinigans We definitely have a problem at least with our input workspace, but it is possible it is something with the workspace and not more general. is there a human-readable way to inspect the values of REF within an existing genomicsDB workspace?

**Comment by bbimber** [comment]
@nalinigans OK, we have more information. Is there other debugging or information we can gather?

- When we take that workspace, run SelectVariants over these intervals and write a new gVCF file, this gVCF reports the REF allele as N. Therefore this isnt specific to GenotypeGVCFs as we originally thought.

- When I tried to make a repro case using the test data from GATK (see the PR linked above), I cant repro this Ns behavior.  Therefore this is something to do with the specific workspace we have, or perhaps how it was created.

Can you suggest additional debugging or tests?

**Comment by mlathara** [comment]
Sorry for the late response - I'm only now getting a chance to look at this. I do want to clarify the exact issue you are raising here, do you expect `--force-output-intervals` to write out sites even when there is no evidence in the gvcf? I'm asking because in the issue describing this (https://github.com/broadinstitute/gatk/issues/7005) you had mentioned something about how GenomicsDBFeatureReader required a reference and wasn't sure if you were implying GenomicsDB would get that info from the reference.

My understanding of `--force-output-intervals` is that it would cause the resulting output to have homref info if there is evidence in the gvcfs (maybe @droazen can clarify/confirm). As such, the fact that you are getting `N` as the REF would suggest that there is no call made for that particular site. In fact, you can see this in the test case you have here. While it doesn't reproduce the issue, if you examine the output vcf file generated by the test:
- Output contains N for `20:10-20` but that is expected because the input gvcf is says as much for the first 9999901 bases
```
20      1       .       N       <NON_REF>       .       .       END=9999901     GT:DP:GQ:MIN_DP:PL      0/0:0:0:0:0,0,0
```
- If you instead change `--force-output-intervals` to `20:9999902-9999910` you will notice that the output file now contains those sites with the right bases and corresponding homref calls:
```
20      9999902 .       T       .       .       .       DP=1    GT:DP:RGQ       0/0:1:3
20      9999903 .       G       .       .       .       DP=3    GT:DP:RGQ       0/0:3:9
20      9999904 .       T       .       .       .       DP=3    GT:DP:RGQ       0/0:3:9
20      9999905 .       T       .       .       .       DP=6    GT:DP:RGQ       0/0:6:18
20      9999906 .       A       .       .       .       DP=6    GT:DP:RGQ       0/0:6:18
20      9999907 .       A       .       .       .       DP=7    GT:DP:RGQ       0/0:7:21
20      9999908 .       A       .       .       .       DP=7    GT:DP:RGQ       0/0:7:21
20      9999909 .       A       .       .       .       DP=9    GT:DP:RGQ       0/0:9:27
20      9999910 .       T       .       .       .       DP=11   GT:DP:RGQ       0/0:11:33
```

Since you replied saying the test isn't reproducing the case you expect, maybe you already know all this - but just wanted to clarify that is the case.

Having said all that, if you're still seeing a case where REF is `N` and you know the input should result in something else, can you share a small snippet of an input gvcf that illustrates the case? Since you were looking at specific intervals in the earlier issue, hopefully you can go back to the input gvcfs for that?

**Comment by bbimber** [comment]
@mlathara To those points:

- Yes, the test case I tried to make using GATK's test data doesnt show this. When I was working quickly I thought I repro'd it, but as you point out the REF bases for chr20:10-20 are actually Ns, so in this instance GenotypeGVCFs is doing the right thing.

- Since my original posts, we figured out new information (posted above). When we simply do a SelectVariants on the genomicsDB workspace over these intervals, it produces a gVCF with Ns listed as the reference. In the actual reference, those sites are not Ns. That's making us look in a different direction than I originally thought. Our current plan is to remake one of our workspaces (exome data from ~800 samples) and see if this repros.

**Pull request closed without merging**
