### PR TITLE
Renames Exon to Target

### PR DESCRIPTION
**Pull request by vruano**
Renamed:
* ExomeReadCounts -> CalculateTargetCoverage
* Exome -> Targets or TargetCollection (Only in code related to the old ExomeReadCounts class.)
* Exon  -> Target (Only in code related to the old ExomeReadCounts class.)

Addresses issue #1252

### CODE REVIEW

**Comment by vruano** [comment]
@LeeTL1220 please take a look. I am renaming the ExomeReadCounts tool to CalculateTargetCoverage. -exome becomes -targets.

**Comment by akiezun** [comment]
@LeeTL1220 do you need this in the alpha build of gatk?

**Comment by vruano** [comment]
What should we do here @LeeTL1220 @akiezun?

**Comment by akiezun** [comment]
:+1: 
rebase and merge at will

**Pull request merged**
