### PR TITLE
clip M2 alleles before emitting in case some alleles were dropped

### PR DESCRIPTION
**Pull request by davidbenjamin**
@sooheelee This is the issue you brought to my attention, and the fix is the method you suggested.  Would you mind reviewing?

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@takutosato giving this to you.

**Comment by takutosato** [comment]
@davidbenjamin could you describe the fix, perhaps with an example?

**Comment by sooheelee** [comment]
I thought I gave an example, with data, in the original issue ticket?

**Comment by sooheelee** [comment]
Here it is again:
https://github.com/broadinstitute/gatk/issues/3506

**Comment by sooheelee** [comment]
And here is the VCF and index: 
[unclipped.tar.gz](https://github.com/broadinstitute/gatk/files/1290857/unclipped.tar.gz)

**Comment by davidbenjamin** [comment]
@takutosato Here's the basic idea: suppose you have a homopolymer context AAA with two potential alt alleles (that is, after assembly), deletions of one and two bases.  Then the ref is AAA and the alts are A and AA.  Now suppose the two-base deletion has too low of a lod to emit.  Then we emit the ref AAA and the alt AA.

Because the A allele is no longer present, this representation is incorrect.  Instead, the ref should be AA and the alt A.  This is what the new clipping line of code does.

**Comment by takutosato** [comment]
@davidbenjamin @sooheelee got it, thanks for the explanation.

**Pull request merged**
