### PR TITLE
Update two instances of '--genotyping_mode' with '--genotyping-mode'

### PR DESCRIPTION
**Pull request by sooheelee**
Documentation update

### CODE REVIEW

**Comment by sooheelee** [comment]
Going forward, @droazen, who should we ask that for review for these minor documentation updates?

**Comment by lbergelson** [comment]
@sooheelee Thank you.  Good catch.

**Comment by lbergelson** [comment]
@sooheelee Anyone on engine team is a good bet to ask for a review for simple documentation changes like this.  For more tool specific complex documentation changes, the tool author/maintainer is probably best.

**Comment by sooheelee** [comment]
Thanks @lbergelson, will do.

**Pull request merged**
