### PR TITLE
VS-991. Wire interval list from Joint Calling through to other workflows #8426

### PR DESCRIPTION
**Pull request by gbggrant**
Defaulting to WGS.
Note that I had to thread the weighted bed file through (and a flag to use it). As this will also be needed to run exomes.

Passing (finally!) Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/199f2e66-4b4b-478c-9370-47a760d3fab2).

### CODE REVIEW

**Review by rsasch — COMMENTED** [review]
Wonder if there's a way to just have one optional input for `GvsJointVariantCalling` that is  `interval_weights_bed` and, if it's passed, `use_interval_weights` will be `true` (otherwise `false`)?

**Comment by gbggrant** [comment]
Yes, I had thought about that, but if I define `interval_weights_bed` as an optional, and default it to the WGS weights bed, then I don't think I can override that to `none` when calling from Terra?

I now think that it might make sense to have a flag `is_wgs` and if true, use the WGS interval list and beds file, and if false, use the Exome interval list and beds file. We could *still* have optional inputs for the interval_list and weights bed and if they were defined use them (and ignore `is_wgs`) - will bring this up in mobbing.

**Comment by gbggrant** [comment]
> Wonder if there's a way to just have one optional input for `GvsJointVariantCalling` that is `interval_weights_bed` and, if it's passed, `use_interval_weights` will be `true` (otherwise `false`)?

Wouldn't that then require the user of `GvsJointVariantCalling` to set the value for `interval_weights_bed` to the default/wgs one every time? I'd prefer to not force a user to do that (and if they neglected to do that, then the WGS workflow would run without weighted intervals)

**Review by rsasch — APPROVED** [review]
I still think this can be simplified to require fewer inputs, but for now LGTM 👍🏻

**Comment by gbggrant** [comment]
I throw my coaches challenge flag.

**Pull request merged**
