### PR TITLE
Remove AuthHolder and dataflow import from BucketUtil 

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Since NIO reportedly now works from Spark clients, this bit of
authentication is unnecessary. Removing it greatly simplifies
BucketUtils, and also stops users having to worry about where
to get the AuthHolder from.

This work is part of #2402

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
All the work is in BucketUtils, the other modified files are just a result of changing the method signatures.

`BucketUtilsTest` pass. Do we have some extra test code that's not run by Travis but that perhaps we should run here? I'm thinking of tests that would spin up a Spark instance and make sure read/write still works as expected.

**Comment by jean-philippe-martin** [comment]
@droazen gentle ping: this code has been awaiting review for two weeks.

**Comment by jean-philippe-martin** [comment]
@droazen weekly ping. Please take a look?

**Comment by droazen** [comment]
@lbergelson Would you have bandwidth to review this one?

**Comment by jean-philippe-martin** [comment]
I have resolved the conflicts, and updated new code that's been added since my original submission of this code that tries to use PipelineOptions.

This is a bit of a race. The longer this PR is sitting, the more people have to write code that deals with PipelineOptions that I then have to go back and remove.

**Comment by lbergelson** [comment]
@jean-philippe-martin 👍 to resolve conflicts and then merge.

**Comment by jean-philippe-martin** [comment]
Resolved conflicts. Once tests are green I'll squash & merge (or you can do it if I forget).

**Comment by lbergelson** [comment]
@jean-philippe-martin Thank you!

**Comment by jean-philippe-martin** [comment]
Thank you @lbergelson !

**Pull request merged**
