### PR TITLE
gave ProcessOptionalArguments in M2 wdl a leaner docker

### PR DESCRIPTION
**Pull request by davidbenjamin**
@LeeTL1220 can you review this if tests pass?

### CODE REVIEW

**Comment by vdauwera** [comment]
Hah I was just about to request this since there's no earthly reason to suck in such a huge image to just run a couple of unix commands :D

**Comment by davidbenjamin** [comment]
Hmmm, I need to figure out why they're not passing.

**Comment by davidbenjamin** [comment]
Okay @LeeTL1220, now it's passing.

**Comment by LeeTL1220** [comment]
@davidbenjamin Looks good.

**Pull request merged**
