### PR TITLE
suppress exception from onShutdown if doWork threw

### LINKED ISSUE #528: Exception in onShutdown mask the actual cause of problems in onStartup.
The current runTool method implementation masks exception occurring in either onStartup or doWork if there is a exception in onShutdown.

It is more important to report the exception in onStartup or doWork that any occurring in onShutdown. 

Apart from this, developers are supposed to make onShutdown robust to failure in onStartup?

### PR DESCRIPTION
**Pull request by lbergelson**
if doWork or onStartup in CommandLineProgram throw an exception then suppress any exception throw in onShutdown
fixes #528

[Review on Reviewable](https://reviewable.io/reviews/broadinstitute/gatk/570)

### CODE REVIEW

**Comment by lbergelson** [comment]
@vruano Please review.

**Comment by akiezun** [comment]
@lbergelson can you propose a solution?

**Comment by lbergelson** [comment]
Closing this for now.  Will resurrect when ready to put time into it.

**Comment by vruano** [comment]
Why close it?

**Comment by lbergelson** [comment]
It's been sitting forever and I haven't gotten back to it.  When I get back to it I'll reopen.  It's just cluttering up the page for now.

**Comment by vruano** [comment]
I would label it a low_priority, I think close it is the same as sentence it to be forgotten into the limbo. There is 219 open issues so I don't see what damage an extra one can do.

**Comment by lbergelson** [comment]
I'm just closing the pull request, no the issue.

**Comment by vruano** [comment]
Ahh! sorry, though was the issue.

**Pull request closed without merging**
