### PR TITLE
Forward input BAM @PG header lines to output BAM

### PR DESCRIPTION
**Pull request by ronlevine**
Implements https://github.com/broadinstitute/gatk/issues/2787.
**Summary of Changes**
* HaplotypeBAMDestination.java - Added a statement to put the the input `@PG` header lines in the output BAM.
* ArtificialReadUtils.java - Added a methods to create a SAM header with Program Records. Fixed a bug in `createArtificialSamHeaderWithReadGroup` where the Read Group was using `PG` instead of the `RG` tag.
* SamAssertionUtils.java - Created a utility, `assertOutBamContainsInBamProgramRecords`, that checks that output BAM file header contains the input BAM file header Program Records.
* SamAssertionUtilsUnitTest.java - Unit tests `assertOutBamContainsInBamProgramRecords`.
* HaplotypeCallerIntegrationTest.java - Tested the input BAM Program Record (PG) tags are forwarded to the output BAM.
* HaplotypeBAMWriterUnitTest.java - Tested the input BAM Program Record (PG) tags are forwarded to the output SAM and BAM.
* testSAM.sam and testBAM.sam - Modified to reflect forwarded PG tags in HaplotypeBAMWriterUnitTest.
* ArtificialReadUtilsUnitTest.java and ReadPileupUnitTest.java - change null to the RG value due to using the correct tag in `ArtificialReadUtils.createArtificialSamHeaderWithReadGroup`.

### CODE REVIEW

**Comment by droazen** [comment]
For @cmnbroad to review

**Comment by droazen** [comment]
@lbergelson will rebase this one later today

**Comment by lbergelson** [comment]
close #2787

**Comment by lbergelson** [comment]
closes #2787

**Pull request merged**
