### PR TITLE
fix bug in M2 engine active region code

### LINKED ISSUE #6901: Possible bug in Mutect2Engine.java
### Affected tool
Mutect2

### Affected version(s)
- [x] Latest public release version 4.1.9.0
- [x] Latest master branch as of 10/19/2020

### Description
It looks like there may be a typo in Mutect2Engine.java that was introduced before the most recent release, https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java#L392

The line currently reads:
```java
if (bestNormalAltAllele.getLeft() == bestNormalAltAllele.getLeft()) {
```
It seems like this line should instead be:
```java
if (bestNormalAltAllele.getLeft() == bestTumorAltAllele.getLeft()) {
```

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6901.  @fleharty

### CODE REVIEW

**Comment by fleharty** [comment]
@davidbenjamin Can we get a regression test for this?

**Comment by fleharty** [comment]
@davidbenjamin Pinging on this.

**Comment by davidbenjamin** [comment]
@fleharty test added.

**Review by fleharty — APPROVED** [review]
Looks great, thanks for adding the test!
Merge away.

**Pull request merged**
