### PR TITLE
Enable query-by-interval of VCFs (including blockgzipped VCFs) on Spark.

### LINKED ISSUE #1651: Enable query-by-interval of VCFs (including blockgzipped VCFs) on Spark

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #1651.

Thanks to @droazen for suggesting the use of `-R` as a source for the sequence dictionary.

### CODE REVIEW

**Comment by tomwhite** [comment]
@akiezun can you have a look?

**Comment by akiezun** [comment]
Tom, when i run 
```
./gatk-launch CountVariantsSpark -V ./src/test/resources/large/dbsnp_138.b37.20.21.vcf.blockgz.gz
```

i get
`Warning: using GzipCodec, which is not splittable, consider using block compressed gzip (BGZF) and BGZFCodec.` 
AFAIK that file is block gzipped - why is the wrong codec used?

**Comment by akiezun** [comment]
it blows up for me when getting the sequence dictionary from the reference. I run this on the cloud
```
./gatk-launch CountVariantsSpark -V hdfs:///user/akiezun/dbsnp_138.b37.20.21.vcf.blockgz.gz -L 20 -R hdfs:////user/akiezun/human_g1k_v37.fasta -- --sparkRunner GCS --cluster dataproc-cluster-3
```

and I get
```
java.lang.IllegalArgumentException: java.net.UnknownHostException: null
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:170)
	at hdfs.jsr203.HadoopFileSystem.<init>(HadoopFileSystem.java:106)
	at hdfs.jsr203.HadoopFileSystemProvider.newFileSystem(HadoopFileSystemProvider.java:165)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:336)
	at org.broadinstitute.hellbender.utils.io.IOUtils.getPath(IOUtils.java:528)
	at org.broadinstitute.hellbender.engine.datasources.ReferenceHadoopSource.getReferenceSequenceDictionary(ReferenceHadoopSource.java:39)
	at org.broadinstitute.hellbender.engine.datasources.ReferenceMultiSource.getReferenceSequenceDictionary(ReferenceMultiSource.java:110)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReference(GATKSparkTool.java:354)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:320)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:311)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:69)
	at org.broadinstitute.hellbender.Main.main(Main.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by tomwhite** [comment]
@akiezun thanks for trying this out. Regarding the wrong codec being used - this is because it wasn't wired up - I've fixed that now.

The `UnknownHostException` is a limitation in the jsr203-hadoop library. It uses the host from the URI to determine the HDFS namenode, and doesn't fall back to the configuration if the URI doesn't have a host. You can work around this by specifying the host in the reference paths. I'll open an issue to fix this.

**Comment by akiezun** [comment]
LGTM. I reran it like this and it works
`./gatk-launch CountVariantsSpark -V hdfs://dataproc-cluster-3-m/user/akiezun/dbsnp_138.b37.20.21.vcf.blockgz.gz -L 21 -R hdfs://dataproc-cluster-3-m/user/akiezun/human_g1k_v37.fasta -- --sparkRunner GCS --cluster dataproc-cluster-3`

the warning is also gone.

**Pull request merged**
