### PR TITLE
Upgrade htsjdk to 2.3.0 and Hadoop-BAM to 7.5.0

### PR DESCRIPTION
**Pull request by tomwhite**
Hadoop-BAM 7.5.0 has not been released yet, so this will fail.

### CODE REVIEW

**Comment by akiezun** [comment]
is the hadoop-bam snapshot available for me to test it?

**Comment by akiezun** [comment]
@lbergelson @tomwhite @droazen can you clarify what needs to be done here? Should we wait from the 7.5.0 release or get the snapshot from somewhere (where?) I want to move forward so that we can make progress on https://github.com/samtools/htsjdk/pull/576

**Comment by tomwhite** [comment]
@akiezun, the snapshot is not available in a repo as it needs https://github.com/HadoopGenomics/Hadoop-BAM/pull/94, which is not yet merged. You can build it yourself easily enough though.

**Comment by droazen** [comment]
Assigning to @akiezun to handle the eventual review/merge

**Comment by akiezun** [comment]
blocked until 7.5.0 is out

**Comment by tomwhite** [comment]
Hadoop-BAM 7.5.0 is out now, so this is ready to be merged.

**Comment by akiezun** [comment]
thanks Tom

**Pull request merged**
