### PR TITLE
Changed order of HDF5/TSV read attempts for CNV read-count collections to avoid native HDF5 warning.

### LINKED ISSUE #4482: Check that HDF5 warnings are caught during CNV TSV/HDF5 reading.
@thebkaufman1995 encountered the following warning when trying to use TSV count files in the gCNV pipeline:

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
 #000: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5F.c line 604 in H5Fopen(): unable to open file
   major: File accessibilty
   minor: Unable to open file
 #001: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5Fint.c line 1085 in H5F_open(): unable to read superblock
   major: File accessibilty
   minor: Read failed
 #002: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
   major: File accessibilty
   minor: Not an HDF5 file
```

My guess is this is because we first try to open counts files as HDF5 and then fall back to TSV (catching the relevant exception).  Perhaps slightly different versions of the HDF5 library result in these warnings being emitted.

### PR DESCRIPTION
**Pull request by samuelklee**
The solution is inelegant and native warnings may still be emitted in some cases within some environments.  However, I think a complete solution may require mucking around with the HDF5 bindings and is probably not worth the trouble.

Closes #4482.

### CODE REVIEW

**Comment by samuelklee** [comment]
@lbergelson mind reviewing this when you get a chance?  Priority is relatively low.  (It's also possible there's a better solution that I'm missing, as this was rather hastily thrown together...)

**Comment by samuelklee** [comment]
@cmnbroad Another short one that might be easy to get in before release.  However, as you can see from the comments here and in the code, there might be a better way to handle this issue.  I was hoping @lbergelson might have some ideas (I think he previously suggested just suppressing stderr/stdout, not sure if that's preferred to hacky try-catches), but if you have bandwidth to review, I'd appreciate any suggestions you might have.

For more context, you can see previous chatter in the dsde-methods Slack channel---just search for HDF5.

**Comment by cmnbroad** [comment]
@samuelklee I think HDF files have a unique signature that is intended to be used to identify them (including a non-ascii first byte to ensure they're not confused with text files). i.e.:

```
~/projects/gatk od -c -N 8 src/test/resources/large/cnv_somatic_workflows_test_files/wes-do-gc.pon.hdf5
0000000  211   H   D   F  \r  \n 032  \n 
0000010
```

We can take this PR for the short-term if you want, but we should add an `isHDF5File` utility method. I think we might be able to use it the CNN tools as well.

**Comment by samuelklee** [comment]
@cmnbroad thanks for looking at this, and good find about the signature.  I think adding `isHDF5File` sounds like the right solution, so I'm happy to push this back.  Will file an issue in that repo---perhaps we can take care of some other issues that have been collecting dust there as well.

**Comment by cmnbroad** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/pull/5082.

**Pull request closed without merging**
