### PR TITLE
Removed @return in javadoc. Added more clarification.

### PR DESCRIPTION
**Pull request by kvinter1**

### CODE REVIEW

**Comment by lbergelson** [comment]
@kvinter1 Welcome to the gatk and congrats on your first pull request.

**Comment by lbergelson** [comment]
@kvinter1 In future, it's a good idea to wait for tests to pass before merging, otherwise you risk the potential penalty of having to buy the team beer if test fail once it's in master.  Doc changes are pretty low risk, but you never know.

**Comment by kvinter1** [comment]
Thanks!

Okay I will make sure to do that in the future. Thanks for the help!

**Comment by lbergelson** [comment]
@kvinter1 No problem, it's confusing since I told you it was good to go.

**Pull request merged**
