### PR TITLE
updating htjsdk to 2.2.0

### PR DESCRIPTION
**Pull request by lbergelson**
adding an htsjdkVersion property since we rely on the version in 2 places in the build

### CODE REVIEW

**Comment by droazen** [comment]
:+1: merge once tests pass

**Comment by akiezun** [comment]
seems like out vcfcodecs stuff broke

**Comment by akiezun** [comment]
```
 org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariantsIntegrationTest.testAlleleTrimming FAILED
    java.lang.RuntimeException: org.broadinstitute.hellbender.exceptions.UserException$NoSuitableCodecs: A USER ERROR has occurred: Cannot read src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/forHardLeftAlignVariantsTest.vcf because no suitable codecs found
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:153)
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:126)
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:108)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariantsIntegrationTest.testAlleleTrimming(SelectVariantsIntegrationTest.java:398)
        Caused by:
        org.broadinstitute.hellbender.exceptions.UserException$NoSuitableCodecs: A USER ERROR has occurred: Cannot read src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/forHardLeftAlignVariantsTest.vcf because no suitable codecs found
            at org.broadinstitute.hellbender.engine.FeatureManager.getCodecForFile(FeatureManager.java:360)
            at org.broadinstitute.hellbender.engine.VariantWalker.initializeDrivingVariants(VariantWalker.java:62)
            at org.broadinstitute.hellbender.engine.VariantWalker.initializeFeatures(VariantWalker.java:55)
            at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:313)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:100)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:152)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:171)
            at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
            at org.broadinstitute.hellbender.Main.instanceMain(Main.java:74)
            at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:65)
            at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:69)
            at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:148)
            ... 3 more
```

**Comment by lbergelson** [comment]
DON'T MERGE YET, on a snapshot build.

**Pull request merged**
