### PR TITLE
upgrading picard 2.18.2 -> 2.18.7

### PR DESCRIPTION
**Pull request by lbergelson**

### CODE REVIEW

**Comment by lbergelson** [comment]
@droazen We had a request to get this in before we release.

**Comment by chandrans** [comment]
Yes, please! Users will be happy :)

**Comment by chandrans** [comment]
Hey Louis and David. A user reports this has not fixed an issue in 4.0.8.1, but the issue is not in latest Picard standalone version. https://gatkforums.broadinstitute.org/gatk/discussion/comment/51988#Comment_51988

**Comment by droazen** [comment]
This is an issue with the GATK arg parser interpreting the ':' character as a tag delimiter. Opened https://github.com/broadinstitute/gatk/issues/5189

**Pull request merged**
