### PR TITLE
VS-1056 support import of PS

### PR DESCRIPTION
**Pull request by gbggrant**
Updates the code to pull the PS field out of gVCFs and stores it in the VET_* table(s).
Note schema change on the VET table
Successful BulkIngest [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Beta%20Test%20ggrant/job_history/5d1f17a9-eeb2-4db3-a681-32d36d9e567e) (run on Exomes as they have PGT, PID, and PS in their gVCFs).
Successful Integration Test Run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/9ab365ff-743b-4d97-9c2a-6a09cf8728f4) - But note that the Exome Integration test failed for slight (and expected) difference in table sizes. I have updated the truth in `gs://gvs-internal-quickstart/integration/2023-07-25-quicker/exome_weighted/table_sizes_expected.csv`

### CODE REVIEW

**Review by mcovarr — COMMENTED** [review]
LGTM once the tests pass

**Review by koncheto-broad — APPROVED** [review]
LGTM!

**Review by mcovarr — APPROVED** [review]
assuming happy tests

**Comment by gbggrant** [comment]
Successful Integration Test Run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/9ab365ff-743b-4d97-9c2a-6a09cf8728f4) - But note that the Exome Integration test failed for slight (and expected) difference in table sizes. I have updated the truth in gs://gvs-internal-quickstart/integration/2023-07-25-quicker/exome_weighted/table_sizes_expected.csv

**Pull request merged**
