### PR TITLE
Exclude htsjdk and protobuf from genomicsdb dependency - Issue 2578

### PR DESCRIPTION
**Pull request by kdatta**
Exclude htsjdk and protobuf from genomicsdb dependency

### CODE REVIEW

**Comment by lbergelson** [comment]
@kdatta Is the version of protobuffs that gatk depends on compatible with the version that genomicsDB needs?

**Comment by kdatta** [comment]
No, they are not compatible. We use the stable version 3.0.2 which uses a base class GeneratedMessageV3 whereas the 3.0.0-beta-1 version uses GeneratedMessage. Hence, we need to build separately for gatk. Having said that, our cmake-based build environment makes it very easy to change protobuf versions. So, this is not a problem.

**Comment by kgururaj** [comment]
Adding to Kushal's comment: the Protobuf generated files distributed as part of the GenomicsDB repo (master branch) are produced using Protobuf 3.0.2. If you clone the source and build the GenomicsDB jar, it will require 3.0.2 and probably fail if you build GATK with the built GenomicsDB jar.

However, if you use the jar that we (Intel team) will upload to Maven central, there will be no issues since the uploaded jar was built using Protobuf v3.0.0-beta1.

**Comment by droazen** [comment]
:+1:

**Pull request merged**
