### PR TITLE
Revert to the previous travis image.

### PR DESCRIPTION
**Pull request by cmnbroad**
to see if the build issues go away.

### CODE REVIEW

**Comment by cmnbroad** [comment]
Based on https://blog.travis-ci.com/2017-08-29-trusty-image-updates. Also see https://github.com/travis-ci/travis-ci/issues/8315.

**Comment by cmnbroad** [comment]
This appears to have succeeded, but I'm not sure if thats just a coincidence. I'm restarting the master build first to see if that passes without this change.

**Comment by SHuang-Broad** [comment]
tried the same fix in another branch and succeeded as well. In the meantime, another branch 20 minutes before this comment without the `.travis.yml` failed in the expected way.

**Comment by cmnbroad** [comment]
Travis support confirms that the new image we're using as of yesterday seems to have less space, and this wasn't being picked up due to the github outage, which is now fixed, and this branch seems to have passed. Once its merged, the builds should APPEAR to be passing again, but then we'll still need to fix the underlying failures in the WDL tests. I'm going to rerun this one more time to verify, since last night I was getting inconsistent results.

**Comment by cmnbroad** [comment]
@SHuang-Broad thx - I'm building this branch one more time to verify, but we should be good after that.

**Comment by cmnbroad** [comment]
@lbergelson Please take a look if you can. This gets the builds passing again, so I'm planning to merge it once the tests pass for a final time.

**Comment by cmnbroad** [comment]
Thx @lbergelson.

**Comment by lbergelson** [comment]
@cmnbroad Do we have an open ticket at travis to track the space issue?

**Comment by cmnbroad** [comment]
@lbergelson https://github.com/travis-ci/travis-ci/issues/8375

**Pull request merged**
