### PR TITLE
Minor doc fixes - addresses issue 3173

### PR DESCRIPTION
**Pull request by vdauwera**
Addresses issue #3173 

I'd welcome advice from @cmnbroad on how to deal with the issue in CalculateContamination where the `@` starting the header lines in the example of Picard interval list breaks the docgen.  My hacky workaround is to add a dot before the @ but it's icky.

### CODE REVIEW

**Comment by vdauwera** [comment]
Ack I meant CollectAllelicCounts

**Comment by cmnbroad** [comment]
@vdauwera You should be able to just replace the "@" with "{@literal @}". You can also use the html entities for these kinds of things, but I can never remember which ones are which.

**Comment by vdauwera** [comment]
ah great thanks @cmnbroad !

**Comment by vdauwera** [comment]
Thanks @lbergelson

**Pull request merged**
