### PR TITLE
Restore old numerics of VQSR temporarily

### PR DESCRIPTION
**Pull request by davidbenjamin**
@drozen @cmnbroad this is for you.

### CODE REVIEW

**Comment by droazen** [comment]
@cmnbroad please review, and confirm that with this branch we can still match GATK3 output

**Comment by cmnbroad** [comment]
These changes look good to me in terms of reverting to GATK3-matching results.

On a separate note though, the optimizations on my branch are largely aimed at reducing unnecessary allocations and boxing, since this (GMM expectation step) is the main hotspot in VQSR, and we iterate through it millions of times. That may conflict with the use of streams as introduced in these PRs (I don't think they introduce any boxing since they use DoubleStreams, but may still result in the same number of array allocation(s) that were in the original code). When I merge in my changes I'll do some more profiling. The stream code certainly looks nicer so it would be nice if we can keep it.

**Comment by droazen** [comment]
I definitely say kill the pretty streaming code if it's harming performance in these critical sections -- no shame in a straightforward loop!

**Comment by davidbenjamin** [comment]
@cmnbroad `MathUtils` has methods like `applyToArray(double[], <lambda>)` that are concise like streams without the overhead.  `IndexRange` has something similar.  Between these and maybe introducing eg `applyToList(List<E>, EToDoubleFunction)` I'd have to imagine we can have both speed and elegance.

**Pull request merged**
