### PR TITLE
removing SHUFFLE

### LINKED ISSUE #1203: delete SHUFFLE from BQSR spark
SHUFFLE is a loser, let's dump it after the broadcast/sharded decision

### PR DESCRIPTION
**Pull request by akiezun**
fixes #1203 

for @droazen

### CODE REVIEW

**Comment by droazen** [comment]
Please rebase to remove conflicts before I review -- back to @akiezun

**Comment by akiezun** [comment]
done. back to @droazen

**Comment by droazen** [comment]
Sending this one back to @akiezun for another rebase.

**Comment by akiezun** [comment]
this is too much pain. i rebased twice. i'll close this PR and I'll think we'll do it from scratch

**Pull request closed without merging**
