### PR TITLE
shl add BETA tag to 19 tools; missing doc tags are resolved in se…

### PR DESCRIPTION
**Pull request by sooheelee**
…parate PRs

### Here are the twelve tools with the BETA tag:
```
CountFalsePositives
HaplotypeCaller
Concordance
GetPileupSummaries
PerformAlleleFractionSegmentation
PerformCopyRatioSegmentation
PerformJointSegmentation
TargetCoverageSexGenotyper
GermlineCNVCaller
CreateAllelicPanelOfNormals
HaplotypeCallerSpark
ConvertACNVResults
```

These include true BETA tools as well as experimental tools. The tag show up as:

screenshot 2017-06-05 17 58 09

### CODE REVIEW

**Comment by sooheelee** [comment]
Tagging many so that each may speak their piece. If there are tools missing from the list that should get the BETA label or an Experimental label, then please speak up.

**Comment by droazen** [comment]
Note that there is no experimental label right now -- just `@BetaFeature`. We may make this more granular in the future, but for now anything that is not production-ready should be marked as `@BetaFeature`

**Comment by sooheelee** [comment]
Added BETA label to 7 SV tools:
```
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AlignAssembledContigsSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/DiscoverVariantsFromContigAlignmentsSAMSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/DiscoverVariantsFromContigAlignmentsSGASpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/FindBadGenomicKmersSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/FindBreakpointEvidenceSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/RunSGAViaProcessBuilderOnSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
```

And changed the program class for DiscoverVariantsFromContigAlignmentsSAMSpark so that instead of showing up under `Spark Tools`, it now groups with the other tools and shows up under `Spark Structural Variation Analysis Tools`.

**Comment by sooheelee** [comment]
I need a yay or nay from each of the teams @cwhelan @samuelklee @davidbenjamin. I will accept yay or nays from @LeeTL1220  on behalf of teams as well. Thanks.

**Comment by davidbenjamin** [comment]
@sooheelee yea.

**Comment by samuelklee** [comment]
:+1:

**Comment by cwhelan** [comment]
OK.

**Comment by sooheelee** [comment]
This is ready to merge @droazen.

**Comment by droazen** [comment]
Looks good to me, but you'll need to rebase the branch to resolve the conflict.

**Comment by droazen** [comment]
:+1: merging

**Pull request merged**
