### PR TITLE
Upgraded Owner to 1.0.10.

### LINKED ISSUE #4490: Update Owner to latest version / new Maven release
Update the Owner version with the latest release from Maven.

### PR DESCRIPTION
**Pull request by jonn-smith**
Fixes #4490 

Release notes:
http://owner.aeonbits.org/news/2018/03/01/owner-1-0-10-released

### CODE REVIEW

**Comment by jonn-smith** [comment]
We need to wait on this until some bug fixes happen in owner.

I have submitted a pull request that will fix the issue I'm seeing

(https://github.com/lviggiano/owner/issues/226)
(https://github.com/lviggiano/owner/pull/227)

**Comment by droazen** [comment]
Closing -- this is blocked by unmerged PRs in Owner. @jonn-smith can re-open once those are accepted. Added links to the PRs in https://github.com/broadinstitute/gatk/issues/4490

**Comment by lviggiano** [comment]
I merged it. 
sorry for the delay.

**Comment by lbergelson** [comment]
@lviggiano Thank you! That's great.

**Pull request closed without merging**
