### PR TITLE
integration tests for SplitNCigarReads

### LINKED ISSUE #1209: SplitNCigarReadsIntegrationTest and SplitNCigarReadsUnitTest are bizzarely similar
SplitNCigarReadsIntegrationTest and SplitNCigarReadsUnitTest are bizzarely similar

something weird is going on. the 'integration test' is not really an intergration test

### PR DESCRIPTION
**Pull request by akiezun**
fixes #1209 
@lbergelson please review

### CODE REVIEW

**Comment by akiezun** [comment]
@lbergelson any clue why git lfs is failing on pull: https://travis-ci.org/broadinstitute/gatk/jobs/97709502

`Git LFS: (9 of 22 files) 67.15 MB / 442.28 MB                                  ls-files`

and fails to download a bunch of files. billing-wise we're fine (checked with @lukwam )

**Comment by lbergelson** [comment]
This is failing due to git lfs failures.  I don't understand why.  I'm asking them for help at https://github.com/github/git-lfs/issues/904

**Comment by lbergelson** [comment]
@akiezun I don't understand why this is failing, but I think we shouldn't commit the tiny bai files to git-lfs.  Better to just have those handled by git itself.  It seems like git-lfs has a small but non-zero cost for every file it checks out, so better to limit it to actually large files.

**Comment by lbergelson** [comment]
@akiezun I'm pushing some changes to this branch to help debug it.

**Comment by vdauwera** [comment]
Btw the GATK3 implementation of this tool generates invalid bam files (because the mate pair info gets all screwed up). If possible to fix that within the tool itself that would be fabulous. Otherwise @yfarjoun has a Palantir ticket to look into a post-hoc fix with FixMateInformation. But it would be nicer to generate valid bams in the first place.

**Comment by lbergelson** [comment]
@vdauwera Could you open a separate ticket for that issue?

**Comment by lbergelson** [comment]
We're basically waiting for help from the git-lfs people on this, which I suspect will be after the holidays.

**Comment by akiezun** [comment]
@lbergelson any update on this issue?

**Comment by lbergelson** [comment]
I'm waiting for a reply from the git-lfs team but I think they've been on vacation.  Hopefully they'll work get back to us soon.  

Git-lfs is showing an error, ssh exiting with status 255, but then it continues and begins downloading  files.  I don't understand what's going on though, and I'm not sure how to dig into it more since it doesn't reproduce locally for me.

**Comment by lbergelson** [comment]
@akiezun This should be fixed now.  I think we're hitting a bug in git-lfs, but I found a simple workaround so once it passes I'm going to merge.

**Pull request merged**
