### PR TITLE
ExcessHet + tests

### LINKED ISSUE #1484: port ExcessHet annotation from GATK3

### PR DESCRIPTION
**Pull request by akiezun**
fixes #1484 
I also refactored the  code duplication between ExcessHet and InbreedingCoef 

@droazen please have a look

### CODE REVIEW

**Comment by droazen** [comment]
Please check in the original versions in a separate commit to make this branch reviewable, and ping me once it's ready. Back to @akiezun

**Comment by akiezun** [comment]
this one is so easy - just open ExcessHet in gatk3

**Comment by droazen** [comment]
And eyeball the changes? I want the diff!

**Comment by droazen** [comment]
Plus we need to start refusing to review ports without the original files included in a separate commit, as a matter of policy -- I've had to do way too much manual diffing with these PRs, which places too much burden on the reviewer.

**Comment by akiezun** [comment]
before you do the port you dont know what files you'll need - that's the main problem

**Comment by droazen** [comment]
That's fine -- you commit the original afterwards (when you're done), overwriting each file in-place with the new names and locations, and then reorder using `rebase -i`

**Comment by akiezun** [comment]
sounds super painful

**Comment by droazen** [comment]
It's not that painful (as explained in person just now) -- it takes on the order of a few minutes.

**Comment by akiezun** [comment]
added originals. I leave the reorder+merge hell to you

**Comment by akiezun** [comment]
@lbergelson can you review? I have some work that is blocked by this
delete the second commit - it's the original code from gatk3

**Comment by lbergelson** [comment]
@akiezun Back to you.  Looks good.  A few nitpicky comments.  I commented directly on the first commit.  Merge when ready.

**Pull request merged**
