### PR TITLE
set Spark reducer chunk size to 64MB by default - speeds up our pipelines

### PR DESCRIPTION
**Pull request by akiezun**
@gspowley can you review and/or delegate to Eric and Lucy?

I confirmed the speedup on MarkDuplicatesSpark - from 9:23 down to 8:54 seconds

### CODE REVIEW

**Comment by droazen** [comment]
Have you confirmed that this doesn't cause problems for `BaseRecalibratorSpark`? I recall that BQSR was the reason the chunk size was set so low originally.

**Comment by akiezun** [comment]
good point

**Comment by akiezun** [comment]
that reemphasizes that we need https://github.com/broadinstitute/gatk/issues/1609 so bad.

**Comment by gspowley** [comment]
Lucy reviewed and said the change looks correct. She is going to test the change on her cluster to verify it is doing what they expect. I'll post her update later today or tomorrow.

**Comment by gspowley** [comment]
Lucy said the changes look good.

**Comment by akiezun** [comment]
this is on hold - the readspipeline is slower on the cloud with this change (using SSDs). I'll close for now

**Pull request closed without merging**
