### PR TITLE
Removed usage of service account from WDLs

### PR DESCRIPTION
**Pull request by gbggrant**
Removed usage of service account from:
GvsAssignIds.wdl
GvsImportGenomes.wdl
GvsCreateAltAllele.wdl
GvsCreateFilterSet.wdl
GvsWithdrawSamples.wdl
GvsCreateAltAllele.wdl
GvsPrepareRangesCallset.wdl
GvsExtractCallset.wdl
GvsExtractCohortFromSampleNames.wdl
GvsUnified.wdl
GvsJointVariantCalling.wdl
GvsAoUReblockGvcf.wdl
GvsBenchmarkExtractTask.wdl
GvsRescatterCallsetInterval.wdl

### CODE REVIEW

**Comment by gbggrant** [comment]
In order to test this, I created a small (10 sample) test set using all of us data. That is [here](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test)
Here are successful runs of the following wdls:
[GvsAssignIds](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/5e56ae8b-4f5f-46cf-bbe9-24aab2a19b3a)
[GvsImportGenomes](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/5c230d7d-79ca-492c-9ee0-b85dc2c709d5)
[GvsCreateAltAllele](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/7006e654-eddb-4a15-a11f-2cf00a69c44d)
[GvsCreateFilterSet](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/b0efe339-46c2-4037-bf94-fcd9d23483f3)
[GvsPrepareRangesCallSet](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/14f0d6db-2865-4f1e-8d85-bf5b1eafd06b)
[GvsExtractCallSet](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/ff484de7-f6e4-488f-b4b9-ce037de514e2)
[GvsCreateVAT](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/aa935629-e6d4-4973-9068-3862c22c703a)
[GvsValidateVAT](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_GVS_NoSA_WDL_Test/job_history/1f450821-d682-4f98-9f6c-37350e2b8b26)

GvsUnified (TODO)
GvsJointVariantCalling (TODO)
GVSCacluatedPrecisionAndSensitivity (unaffected)
GvsCallsetCost (unaffected)
GvsJointVariantCallingCallsetCost (unaffected)
GvsQuickstartIntegration (unaffected)
GvsAoUReblockGvcf (TODO)
GvsRescatterCallsetInterval (TODO??)
GvsBenchmarkExtractTest (TODO??)

**Review by mcovarr — APPROVED** [review]
yesss 👍 👍 👍 (once all the WDLs have tested out)

**Review by rsasch — APPROVED** [review]
LGTM!  I would definitely test `GvsAoUReblockGvcf.wdl` to make sure that we don't need the SA to access where the un-blocked gVCFs are.  And we should probably give AoU (Tarek/Shimon) a heads up that the `ExtractCohortFromSampleNames` WDL won't have the SA anymore (I don't know how it was run in the past).

**Comment by mmorgantaylor** [comment]
Confirmed that `GvsAoUReblockGvcf.wdl` works 👍

**Pull request merged**
