### PR TITLE
upgrade log4j to 2.17

### PR DESCRIPTION
**Pull request by kcibul**

### CODE REVIEW

**Review by rsasch — APPROVED** [review]
LGTM (🤞🏻 the tests pass)

**Review by ahaessly — APPROVED** [review]
👍

**Comment by aofarrel** [comment]
@lbergelson I cannot update #7611 with these changes until the Docker image(s) are regenerated, as WDL workflows (in this context) point to a Docker image. Since an image with these changes isn't currently on DockerHub, those workflows remain insecure.

I would like to propose tagging a new release (4.2.4.1) that contains #7616 and pushing those as tag 4.2.4.1 onto DockerHub. Once that is done, I can update the workflows accordingly.

**Comment by lbergelson** [comment]
@aofarrel Yes, I'm going to do that very soon.

**Pull request merged**
