### PR TITLE
switched CigarBuilder's order for adjacent indels to be deletion first

### LINKED ISSUE #6473: Mutect2 (GATK 4.1.5.0) emitting MNPs despite max-mnp-distance 0
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
- [x] Latest public release version 4.1.5.0

#### Steps to reproduce
It seems that Mutect2 is emitting MNPs despite `--max-mnp-distance 0`

1. Calling in tumor-only mode to prep PON:
```
Using GATK jar /gatk/gatk-package-4.1.5.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx20G -jar /gatk/gatk-package-4.1.5.0-local.jar Mutect2 --max-mnp-distance 0 --input /mnt/data/input/gs/file.bam.cram --reference /mnt/data/input/gs/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta --germline-resource /mnt/data/input/gs/ukbb_v2/projects/jamesp/data/mutect2/bravo-dbsnp-all-f5.exome.chr.sorted.reheader.vcf.gz --intervals /mnt/data/input/gs/gcp-public-data--broad-references/hg38/v0/exome_calling_regions.v1.interval_list --output /mnt/data/output/gs/file.bam.cram.unfiltered.vcf.gz
```

2. GenomicsDB creation for PON step:
```
Using GATK jar /gatk/gatk-package-4.1.5.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx40G -jar /gatk/gatk-package-4.1.5.0-local.jar GenomicsDBImport --reference /mnt/data/input/gs/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta --intervals chr1 --intervals chr2 --intervals chr3 --intervals chr4 --intervals chr5 --intervals chr6 --intervals chr7 --intervals chr8 --intervals chr9 --intervals chr10 --intervals chr11 --intervals chr12 --intervals chr13 --intervals chr14 --intervals chr15 --intervals chr16 --intervals chr17 --intervals chr18 --intervals chr19 --intervals chr20 --intervals chr21 --intervals chr22 --intervals chrX --genomicsdb-workspace-path pon_db {etc}

***********************************************************************

A USER ERROR has occurred: Bad input: GenomicsDBImport does not support GVCFs with MNPs. MNP found at chr1:1914706 in VCF /mnt/data/input/gs/file.bam.cram.unfiltered.vcf.gz
```

#### Expected behavior
I would expect no MNPs if Mutect2 is run in `--max-mnp-distance 0` mode.

#### Actual behavior
There are apparently MNPs, so it seems that `--max-mnp-distance 0` has no effect?

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6473 and resolves a few forum issues about GenomicsDB not supporting MNPs.

@ldgauthier

### CODE REVIEW

**Comment by davidbenjamin** [comment]
> but I thought you said you'd add a regression test with the user's data

I must have.  There is a regression test now.

**Comment by mlaylwar** [comment]
I am experiencing this issue, which I thought was solved. I have used version 4.1.7.0 haplotype caller, then when I use combineGVCFs I receive the error: A USER ERROR has occurred: Bad input: Combining gVCFs containing MNPs is not supported. Unknown contained a MNP at A1:684599

I didn't set any value for -max-mnp-dist as the docs say that default is already set to 0. Any idea how to get around this error?

Thanks

**Comment by davidbenjamin** [comment]
@mlaylwar What are the reference and MNP alleles at this position?

**Comment by mlaylwar** [comment]
I don't have these files anymore I'm afraid. I can probably recreate if
necessary

**Pull request merged**
