### PR TITLE
Shl doc archive 2

### PR DESCRIPTION
**Pull request by sooheelee**
It would be good to also delete empty folders created by deleting code.

Ask if `git clean -fd` is appropriate. First run `git clean -fdn` to check what may be removed.

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@sooheelee I believe these are all obsolete but I would want @samuelklee's approval before deleting.

**Comment by samuelklee** [comment]
:+1:

**Comment by sooheelee** [comment]
@samuelklee @davidbenjamin I'm not authorized to merge PRs, so one of yous will have to.

**Comment by davidbenjamin** [comment]
@droazen I'm not authorized either.

**Pull request merged**
