### PR TITLE
Make new qual the default in HaplotypeCaller and GenotypeGVCFs

### PR DESCRIPTION
**Pull request by davidbenjamin**
@ldgauthier this shouldn't get merged before #5460.

### CODE REVIEW

**Comment by ldgauthier** [comment]
@droazen this needs to go in the 4.1 release, but the rebase is potentially going to be a little hairy.

**Comment by davidbenjamin** [comment]
The rebase might not be too bad.  I've done it before, after all.  I will do my best to finish it tonight.

**Comment by davidbenjamin** [comment]
HaplotypeCaller, GenotypeGVCFs, and GenomicsDBImport integration tests are all passing locally.  I'll check Travis in the morning to see what tests are left to update.

**Comment by davidbenjamin** [comment]
This one's a bit thornier than it was before but I just fixed locally the sole discrepancy that Travis reported.  This push might do it. . .

**Comment by davidbenjamin** [comment]
@ldgauthier Ready for you to look at.

**Comment by droazen** [comment]
No additional changes that might affect the `HaplotypeCaller` output are slated to be merged before the 4.1 release tomorrow, so today would be a good time to get this one in @ldgauthier @davidbenjamin

**Pull request merged**
