### PR TITLE
Move BigQuery classes [VS-971]

### PR DESCRIPTION
**Pull request by mcovarr**
Move BigQuery classes that are only used by GVS into a `gvs` package. This should facilitate the alignment of GVS with GATK master by making it clear that these classes were created specifically for GVS and are not necessarily more generally usable in their current forms.

### CODE REVIEW

**Review by koncheto-broad — APPROVED** [review]
LGTM.  Appear to just be moving packages and a bit of formatting.

**Review by gbggrant — APPROVED** [review]
Looks good to me.

**Comment by droazen** [comment]
@mcovarr Does the GVS traversal artifact destined to remain in GATK depend on the `BigQueryUtils`? I'm guessing that it does? Is the intention that `BigQueryUtils` would remain in gatk/master, then, just in a different package?

**Comment by mcovarr** [comment]
@droazen exactly, the artifact will depend on `BigQueryUtils` which would be in a `gvs` package to hopefully make clear that the contents are currently fairly specific to GVS and probably not ideal for more general use in their present form.

**Pull request merged**
