### PR TITLE
move PCA and hdf5 from protected

### PR DESCRIPTION
**Pull request by akiezun**
fixed another part of #1427 

notes: 
PCA was moved to the SVD package rather than its own (1 class in a package was a bad smell)
No PoN-related code was moved, only generic HDF5 code

### CODE REVIEW

**Comment by akiezun** [comment]
@lbergelson   can you review?

**Comment by lbergelson** [comment]
do we want this in protected?  It means people have to go through arcane installation procedures...

**Comment by akiezun** [comment]
most people get protected. I'd rather push the pain down to public (unless
it doubles the pain and both repos need this).

Oh btw, perhaps we should spin off the HDF5 to a separate project that we
would just inject in gatk
wdyt?

**Comment by lbergelson** [comment]
+1 to spinning off HDF5.  We should package it and make it available as a jar with the native code included.  I'm pretty sure we can do so legally.

**Comment by lbergelson** [comment]
there's an open ticket https://github.com/broadinstitute/gatk-protected/issues/436 to spin off hdf5

**Comment by akiezun** [comment]
i'll close this and spinoff hdf5

**Pull request closed without merging**
