### PR TITLE
corrected javadoc for InbreedingCoeff

### LINKED ISSUE #5712: InbreedingCoeff javadoc claims value is "phred-scaled p-value" but actual value is neither phred-scaled nor a p-value
### Tool(s) or class(es) involved
`InbreedingCoeff` variant annotation

### Description 
The javadoc, and from there the generated website documentation, describes the value as being a phred-scaled p-value.  However, looking at the values produced and also the code it would appear to be the non-transformed value `1 - observed_hets / expected_hets`.

----

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #5712.

@ldgauthier can you look at this?

### CODE REVIEW

**Comment by ldgauthier** [comment]
How can F be a probability when it takes on negative values?

Also, I've never heard of it being called the Fixation Score.  Is that in one of your stat gen books?

**Comment by davidbenjamin** [comment]
> How can F be a probability when it takes on negative values?

It's the probability of alleles being IBD *provided that inbreeding is the only source of deviation from HWE* and in the limit of infinite sample size washing out statistical noise.  Under these assumptions it's always positive.  How about I rewrite the docs to be much, much clearer about this?

> Also, I've never heard of it being called the Fixation Score.

I hadn't heard of it, either, but Wikipedia told me so: https://en.wikipedia.org/wiki/F-statistics

**Comment by davidbenjamin** [comment]
Switched to cosanguinuity.

**Comment by ldgauthier** [comment]
I don't think that's a word: https://www.merriam-webster.com/dictionary/consanguinity

**Comment by davidbenjamin** [comment]
Oh no!

**Pull request merged**
