### PR TITLE
Add a doc build command line argument to emit php doc files.

### PR DESCRIPTION
**Pull request by cmnbroad**

### CODE REVIEW

**Comment by vdauwera** [comment]
Ah this is great, thanks @cmnbroad. Do I understand correctly that the new usage will be `./gradlew gatkDoc -PphpDoc` ?

**Comment by cmnbroad** [comment]
Right. And just "./gradlew gatkDoc" (with no arg) for html.

**Comment by vdauwera** [comment]
Perfect, thank you 👍

**Comment by droazen** [comment]
Would it be better/simpler to just have both `./gradlew gatkDoc` and `./gradlew phpDoc`?

**Comment by droazen** [comment]
Needs to be rebased onto latest master so that tests can pass in travis.

**Comment by vdauwera** [comment]
Doing it now

**Comment by vdauwera** [comment]
@droazen re: your earlier question, I think it's preferable to use the same base command and add a qualifier -- we may add other output format shortcuts in future, and I find it more intuitive to specify the format as an extra arg rather than a different target altogether.

**Comment by vdauwera** [comment]
@cmnbroad This branch is failing, I don't know why (don't understand the failures). I just rebased it on latest master, which passes everything afaict.

**Comment by droazen** [comment]
@vdauwera Well, the full truth is that the M2 WDL tests are experiencing intermittent failures at the moment due to out-of-disk-space issues on travis. You can safely merge this if only the M2 WDL tests failed.

**Comment by cmnbroad** [comment]
Yeah, this failure looks the same as the others, and unrelated to this change.

**Comment by vdauwera** [comment]
splendid -- then i will merge it.

**Pull request merged**
