### PR TITLE
Code Review for #8752

### PR DESCRIPTION
**Pull request by bbimber**
This is responding to code review on #8752

### CODE REVIEW

**Comment by bbimber** [comment]
@lbergelson or @droazen: this is related to your comments on #8752 about preserving the default behavior of just writing the first source. This PR overloads simpleMerge(), meaning code needs to opt-in to the feature of preserving all source names. 

I cannot kick off tests - would one of you be able to to that?

**Comment by bbimber** [comment]
@jamesemery, thanks for kicking off tests. the compile failure is probably due to a bad merge. I pushed a fix - would you be able to restart tests?

**Comment by jamesemery** [comment]
@bbimber The test that failed just got fixed in master so you should be good to ignore it... it is @lbergelson PR into your code that you are patching so i don't know if he should approve this or not...

**Comment by bbimber** [comment]
> @bbimber The test that failed just got fixed in master so you should be good to ignore it... it is @lbergelson PR into your code that you are patching so i don't know if he should approve this or not...

Thanks @jamesemery. The PR in question was initiated by me, but having @lbergelson approving seems fine. The goal here is to get https://github.com/broadinstitute/gatk/pull/8752 approved.

**Comment by bbimber** [comment]
Closed in favor of: https://github.com/broadinstitute/gatk/pull/9032

**Pull request closed without merging**
