### PR TITLE
use snappy and 512k blocks

### PR DESCRIPTION
**Pull request by akiezun**
improvement proposed by folks at Intel - in my tests it improves performance of MarkDuplicatesSpark by >10% 

@gspowley can you review and/or ask Eric+Lucy ?

### CODE REVIEW

**Comment by gspowley** [comment]
The changes look good to me. I'll ask Lucy to take a look too.

**Comment by gspowley** [comment]
Lucy reviewed and said the changes look good.

**Comment by akiezun** [comment]
Argh, this is not working for me on CDH (it works on google cloud), I get:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.xerial.snappy.SnappyNative.maxCompressedLength(I)I
	at org.xerial.snappy.SnappyNative.maxCompressedLength(Native Method)
	at org.xerial.snappy.Snappy.maxCompressedLength(Snappy.java:316)
```

@tomwhite any idea why snappy is not working on CDH 5.7 for us?

**Comment by akiezun** [comment]
I'm reverting this until we can make it work on CDH.

**Pull request merged**
