### PR TITLE
methylation walker

### PR DESCRIPTION
**Pull request by benjamincarlin**
This is a first draft/iteration on my CEMBA Type Caller in order to jump start the review process. Here are some of my own suggestions to add:

Add Tests with a sample methylated bam as input and a corresponding vcf as expected exact match output
Add constants for VCF header names
Add constants for VCF header descriptions 
Change program group

### CODE REVIEW

**Comment by droazen** [comment]
@benjamincarlin Did you intend to close this one?

**Comment by benjamincarlin** [comment]
I was push an old branch and needed to pull from master and rebase. So I closed this one to avoid confusion

**Comment by lbergelson** [comment]
@benjamincarlin You can always force push over one of your branches.  You don't have to create a new PR.

**Comment by benjamincarlin** [comment]
@lbergelson Thanks, makes sense! Will do next time!

**Pull request closed without merging**
