### PR TITLE
update Readme with new script name and location

### PR DESCRIPTION
**Pull request by akiezun**

### CODE REVIEW

**Comment by lbergelson** [comment]
@akiezun is this true?  It doesn't work for me.  I think we have to change the name in build.gradle before this will switch

**Comment by akiezun** [comment]
it's true for me.

**Comment by lbergelson** [comment]
interesting

**Comment by lbergelson** [comment]
Strange.  It's based on the folder name.

**Comment by lbergelson** [comment]
:+1:

**Pull request merged**
