### PR TITLE
Make several Funcotator methods and fields protected

### PR DESCRIPTION
**Pull request by bbimber**
Make several Funcotator methods and fields protected so it is easiest to extend the tool

### CODE REVIEW

**Comment by bbimber** [comment]
@jonn-smith would it be possible to make two more methods public, this time from FuncotatorEngine? If so, would it be possible to push a nightly build, similar to what @lbergelson did here: https://github.com/broadinstitute/gatk/issues/8138

**Comment by bbimber** [comment]
@jonn-smith: sorry to bug, but wanted to see if you'd approve this minor PR.

**Review by lbergelson — APPROVED** [review]
This looks good to me.  Just waiting on the tests.  Jonn is sick this week but this should be fine I think.  I'll push a snapshot when this goes in.

**Comment by bbimber** [comment]
@lbergelson: thanks for your help. looks like the tests passed

**Comment by lbergelson** [comment]
@bbimber I pushed it up as `4.3.0.0-33-gd1a4f94-SNAPSHOT`

**Pull request merged**
