### PR TITLE
Update to gcloud NIO 0.19.0

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Along with minor changes needed to track the moved classes
and changed interfaces.

This is related to issue #2822

### CODE REVIEW

**Comment by droazen** [comment]
@jean-philippe-martin We want `0.19.0`, I believe.

**Comment by droazen** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-java/releases/tag/v0.19.0

**Comment by jean-philippe-martin** [comment]
updated to 0.19

**Comment by droazen** [comment]
@jean-philippe-martin You're going to have to rebase this branch onto the latest master in order to pass tests, due to a change @lbergelson made in master.

**Comment by jean-philippe-martin** [comment]
@droazen done

**Comment by jean-philippe-martin** [comment]
Wonderful, thank you!

**Comment by droazen** [comment]
@jean-philippe-martin We are testing this internally now to see if it resolves our GCS connection issues -- fingers crossed!

**Pull request merged**
