### PR TITLE
CNV performallelefractionsegmentation: tag doc

### PR DESCRIPTION
**Pull request by sooheelee**
with documenetedfeature tag so it shows up in autodoc generation.

### CODE REVIEW

**Comment by sooheelee** [comment]
Yikes, says ten files have changed. Nine are `File renamed without changes.`.

**Comment by droazen** [comment]
@sooheelee Recommend we do this together on Monday -- it's slightly tricky to do correctly, especially if there were multiple commits on the original protected branch. In the mean time, you should probably close the PRs in which the diff isn't right.

**Comment by sooheelee** [comment]
@droazen I made a new branch from the merged repo. This one isn't a migrated PR.

**Comment by sooheelee** [comment]
I am closing this.

**Pull request closed without merging**
