### PR TITLE
GVS walker to master [VS-964]

### PR DESCRIPTION
**Pull request by mcovarr**
Ready for review!

### CODE REVIEW

**Review by KevinCLydon — CHANGES_REQUESTED** [review]
This looks just about good to me. I left a couple comments, mostly questions and some very minor changes.  Beyond those, I have another question and a couple more suggestions:

1. Codecov claims a lot of this code doesn't have tests.  Am I correct to assume that is because it mostly relies on BigQuery and is therefore prohibitively difficult to write tests for?
2. The code is mostly stylistically good, but there are a lot of places where variables, especially method parameters, that should be `final` are not, so it would be good to do a quick pass and update those if possible.
3. Most of this code could benefit from more documentation.  Some of it is very well documented, but some of the files don't seem to have much at all.  It would be good to at least have doc comments for the public classes and any public attributes and methods that are not immediately self-explanatory by their names.

Thank you for doing the work to get this merged into master.

**Comment by mcovarr** [comment]
> @mcovarr @koncheto-broad Do all these files exist as they are here in the ah_var_store branch currently?

Yes, delta the refactoring required to separate the VCF writing into a subclass.

**Comment by KevinCLydon** [comment]
> > @mcovarr @koncheto-broad Do all these files exist as they are here in the ah_var_store branch currently?
> 
> Yes, delta the refactoring required to separate the VCF writing into a subclass.

Would it be easier/preferable for you all to move those changes into the var store branch and I'll work on the PGEN stuff there instead of in master?

**Comment by mcovarr** [comment]
Hi @KevinCLydon, yes actually all of this is on `ah_var_store` already per [an earlier PR](https://github.com/broadinstitute/gatk/pull/8344). Sorry my earlier comment was incorrect, this was > 1 month ago and I forgot 😅

**Comment by droazen** [comment]
@mcovarr @koncheto-broad Had a talk today with @KevinCLydon about this PR, and he made a convincing case that the pgen project is more likely to require additional stuff from the GVS branch than from gatk/master. To avoid a nightmare scenario of constantly having to request additional transplants from the GVS branch, I'm on board with the idea of having Kevin try to work off of the GVS branch for the pgen project for now, provided that we can get timely rebases of `ah_var_store` onto master if we need them.

**Comment by mcovarr** [comment]
Thanks @droazen, I'll go ahead and close this PR. The equivalent GVS walker code is already on `ah_var_store`, but the syncing up of `ah_var_store` to `master` is still on the TODO list.

**Pull request closed without merging**
