### PR TITLE
Issue 569 - bam and sam file cleanup.

### PR DESCRIPTION
**Pull request by nenewell**
This addresses issue 569 - the cleanup of format errors in bam and sam files in tests. I will send an archive with a README, validations for the post-modification bams and sams, and diffs for the bams to akiezun.

### CODE REVIEW

**Comment by nenewell** [comment]
These changes pass all tests on my system but the Travis build fails in 30 seconds - security issue?

**Comment by lbergelson** [comment]
Yeah.  The tests aren't running properly from forks since we started including keys for google cloud.  I need to update them so they run the tests that they can run instead of failing.

**Comment by nenewell** [comment]
Thanks for letting me know.

**Comment by lbergelson** [comment]
@nenewell Sorry this has been sitting.  We've been trying to figure out how to review this one.  Could you describe how you made the changes?  Did you script it or go through by hand and modify them all?

**Comment by nenewell** [comment]
No problem – I can see how this would be challenging to review – maybe it’s not even practical – if you decide it’s best just not to use it that’s OK  - working on these issues has been a valuable learning experience for me. 

I sent an archive with the new validations and the diffs between the old and new bams to akiezun. Although in many cases the files shared types of errors, I had to look at each file individually to take into account the particular errors in each file and how to fix them without (to the best of my knowledge) interfering with the purpose of the test. I did write a python script to use where necessary for converting multiple unpaired reads in a file to single reads, and I used bash scripts to call the picard tools to convert multiple files at a time from bam to sam for editing and then back again after they were modified. In some cases I had to modify the values in test output files to match the values produced by the test using the modified bams/sams, or just capture the new output files and use them to replace the old with the new. In two cases where file format errors appeared to be necessary but the filename did not indicate this, I renamed the files to make this clear.

**Comment by akiezun** [comment]
@droazen @lbergelson what's the decision here?

**Comment by akiezun** [comment]
i'm closing this - it'd be too hard to review. Thanks again @nenewell for your contribution, sorry we're not able to review it properly.

**Comment by nenewell** [comment]
No problem – understood.

**Pull request closed without merging**
