### PR TITLE
Updated the stats script to be more easily used.

### PR DESCRIPTION
**Pull request by jonn-smith**

### CODE REVIEW

**Comment by droazen** [comment]
@jonn-smith Has this new version of the script been tested / is it in actual use?

**Comment by jonn-smith** [comment]
Yeah - I gave it to @rickymagner to use on one of his repos

**Comment by droazen** [comment]
@jonn-smith But is it being used for the GATK stats, or is that still using an older version?

**Comment by jonn-smith** [comment]
Ah, I misunderstood.

Yes - it's using this version

**Review by droazen — APPROVED** [review]
+1

**Pull request merged**
