### PR TITLE
Port ConstrainedMateFixingManager from GATK3

### PR DESCRIPTION
**Pull request by magicDGS**
As part of #3104

### CODE REVIEW

**Comment by magicDGS** [comment]
Could you nominate someone for this one, @droazen?

In addition, I would like to use the `GATKRead` interface instead of `SAMRecord`, but I do not look into the logic enough to do the change yet...

**Comment by droazen** [comment]
For @cmnbroad to review when he has the time

**Comment by magicDGS** [comment]
@cmnbroad - any chance to get to this one?

**Comment by magicDGS** [comment]
@cmnbroad - this is also part of the port of indel realignment, which should be easier to review because it is not a tool but a helper class (thus, documentation and arguments formatting shouldn't be a problem here).

**Comment by magicDGS** [comment]
Closing (will be part of a bigger PR with the port for both tools from the pipeline)

**Pull request closed without merging**
