### PR TITLE
Added bc to docker file.

### LINKED ISSUE #5494: Add bc to baseline docker image
For the automated regression pipelines, I would like to add `bc` and possibly other programs to the docker image.

### PR DESCRIPTION
**Pull request by jonn-smith**
Fixes #5494

### CODE REVIEW

**Comment by lbergelson** [comment]
I wrote a very minimal guide that says the same thing here: https://github.com/broadinstitute/gatk/wiki/How-to-update-the-gatk-base-docker

**Comment by droazen** [comment]
@jonn-smith Do you want to finish this branch up following @lbergelson 's instructions above, or would you prefer to close this?

**Comment by jonn-smith** [comment]
@droazen Yeah - I think this should be in there.  I'll go through his instructions to get it into the base image.

**Comment by lbergelson** [comment]
closing since this was included in https://github.com/broadinstitute/gatk/pull/5593

**Pull request closed without merging**
