### PR TITLE
more missing pieces of HC

### PR DESCRIPTION
**Pull request by akiezun**
for @droazen

a lot of legacy code here with suboptimal test coverage. I only did a very shallow pass over the style issues. I'm mostyl looking for feedback on whether some of those pieces are not needed. I can deal with style later in the review

### CODE REVIEW

**Comment by droazen** [comment]
@akiezun Before I review this, could you please:

1. Create a commit with the GATK3 versions of each file added or substantially changed here.

2. `git rebase -i 10d9ec1080bc08fa0da00151d1c76c5d1336054e`, and reorder the two commits so that the one with the originals comes first. You'll likely get two merge conflicts when you do this. In the first merge conflict, accept all the GATK3 versions of the files, and in the second, accept all of the GATK4 versions.

3. `git diff HEAD origin/ak_GenotypingEngine_part2`, and make sure there are no differences as a result of the rebase before pushing.

**Comment by akiezun** [comment]
as discussed with @droazen, I'm not touching this PR until he's done with his experiment. Reassigning to make it clear that I'm not working on this.

**Comment by droazen** [comment]
I've backed up the state of these HC branches and have started the process of merging them with my engine work into a runnable tool. Feel free to address to code review comments whenever you like, as it won't affect my work now. Back to @akiezun

**Comment by akiezun** [comment]
@droazen this sounds complicated. how about i just make a separate branch with the original files?

**Comment by droazen** [comment]
@akiezun It's not that complicated -- will take ~5 minutes, and I provided the git commands. A separate branch is not as reviewer-friendly.

**Comment by akiezun** [comment]
ok, it was bad as i expected.
I completed step 1. Steps 2 and 3 are for you.

**Comment by droazen** [comment]
I've "taken over" this branch -- it will be absorbed into my upcoming HC PR.

**Pull request closed without merging**
