### PR TITLE
Use Dataproc 1.2 which supports Spark 2.2.1

### PR DESCRIPTION
**Pull request by tomwhite**
Simple update to use the correct version of Spark in the scripts.

### CODE REVIEW

**Comment by cwhelan** [comment]
I just noticed this but wanted to pass along the tidbit that with the SV tools we moved to Dataproc 1.3 (and Spark 2.3.0) because we started hitting errors like this:

`java.io.IOException: Failed to create local dir in /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1535480872324_0648/blockmgr-1193ec43-c523-423b-bd88-e40ee0102cca/24`

In large jobs running on with the Dataproc 1.2 image after Google released Dataproc 1.3. I also hit the error trying to run Hail the other day and filed an issue with Google here:

https://issuetracker.google.com/issues/113360059

**Comment by lbergelson** [comment]
@tomwhite @cwhelan Should we update our spark dependencies to 2.3.0 then?

**Comment by cwhelan** [comment]
@lbergelson Our stuff runs fine using Dataproc image 1.3 and the current GATK dependencies, so I guess it's not crucial, but it's probably something we should investigate doing?

**Comment by tomwhite** [comment]
Thanks for letting me know about this @cwhelan. I agree we should look at using Dataproc 1.3 for the Spark scripts at least (#5152).

**Pull request merged**
