### PR TITLE
remove support for SOLID from BQSR

### LINKED ISSUE #971: Optimize SOLID lookup in BQSR

### PR DESCRIPTION
**Pull request by akiezun**
fixes #971 
The reason for removal is that checking if a read is Solid took 10% of runtime and we (Broad) does not have any Solid data.

### CODE REVIEW

**Comment by lbergelson** [comment]
Should we have an upfront check that none of the read groups have solid data since we know it will now give wrong answers if they are?

**Comment by vdauwera** [comment]
Yes please. Should definitely check for supported/unsupported technology.

**Comment by lbergelson** [comment]
I added this check in the branch where I started to do this.

```
private void assertNoSOLiDReadGroups(SAMFileHeader readsHeader) {
    if (readsHeader.getReadGroups().stream().anyMatch(rg -> NGSPlatform.fromReadGroupPL(rg.getPlatform()) ==  NGSPlatform.SOLID)){
       throw new UserException.BadInput("BQSR does not support SOLiD data but found read group from solid platform.");
    }
}
```

**Comment by akiezun** [comment]
@lbergelson please review

**Comment by lbergelson** [comment]
:+1:

**Pull request merged**
