### PR TITLE
improving error message in GATKSparkTool.writeReads

### PR DESCRIPTION
**Pull request by lbergelson**
changing from GATKException to the more appropriate UserException.CouldNotCreateOutputFile
updating user exceptions that take an exception to properly pass the exception on as their cause so they don't show incomplete stack traces

### CODE REVIEW

**Comment by lbergelson** [comment]
@droazen I noticed that exception causes were getting lost while looking into the gcs issue, this should fix some of that.

**Comment by magicDGS** [comment]
Maybe the part of stack trace should be included in #2282 too? Because I'm working on every `UserException`, I think that it will be important for all the new constructors...

**Comment by lbergelson** [comment]
@magicDGS I think if you're adding new constructors that take an exception as a parameter they should probably propagate it to the super constructor.  I

**Comment by droazen** [comment]
:+1: merge when ready

**Pull request merged**
