### PR TITLE
Changed VariantFiltrationDoc

### PR DESCRIPTION
**Pull request by chandrans**
VariantFiltration GATK4 Doc

### CODE REVIEW

**Comment by sooheelee** [comment]
`-o` to `-O`?

**Comment by vdauwera** [comment]
@chandrans you missed quite a few instances of -o/-O and some other syntax updates (like dropping the -T).

**Comment by vdauwera** [comment]
can be merged once tests pass

**Comment by chandrans** [comment]
Yea. I am still making the -o mistake when running Mutect tutorial commands. Sorry about that.

**Pull request merged**
