### PR TITLE
Added ability to edit intervals in GATKSparkTool subclasses

### PR DESCRIPTION
**Pull request by LeeTL1220**
@droazen has reviewed (over my shoulder) and says it looks good.

### CODE REVIEW

**Comment by LeeTL1220** [comment]
@lbergelson Can you release a snapshot that includes this pull request?  (And send me the snapshot, so that I can, most likely, kick off a workflow tonight)

**Comment by droazen** [comment]
:+1: merging

**Comment by lbergelson** [comment]
@LeeTL1220 Going to upload this when I get home.  My bandwidth is too bad at the coffee shop I'm sitting in.

**Comment by lbergelson** [comment]
@LeeTL1220 org.broadinstitute:gatk:4.alpha.1-15-g3881040-SNAPSHOT

**Comment by LeeTL1220** [comment]
@lbergelson Awesome!  Thanks

**Pull request merged**
