### PR TITLE
palindrome ITR artifact transformer skips reads whose contigs are not in sequence dictionary

### LINKED ISSUE #6851: Mutect2 BAM contigs not in reference
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
4.1.8.1

### Description 
A user is getting a java.lang.NullPointerException when running Mutect2. As discussed at GATK Office Hours 09/28/20, it seems to be an issue where the BAM contigs are not present in the reference sequence dictionary. We discussed an improvement with either the filter for this problem or the error message.

Complete stack trace:
```
Using GATK jar GATK/4.1.8.1-GCCcore-9.3.0-Java-1.8/gatk-package-4.1.8.1-local.jar
Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx16g -jar /GATK/4.1.8.1-GCCcore-9.3.0-Java-1.8/gatk-package-4.1.8.1-local.jar Mutect2 -R ref/Homo_sapiens_assembly38.fasta -I SRR_MM10_2pass_recal.bam --germline-resource /af-only-gnomad.hg38.vcf.gz --panel-of-normals ref/1000g_pon.hg38.vcf.gz -O SRR_somatic_mutect.vcf.gz
13:24:08.400 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/GATK/4.1.8.1-GCCcore-9.3.0-Java-1.8/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Sep 25, 2020 1:24:08 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
13:24:08.556 INFO Mutect2 - ------------------------------------------------------------
13:24:08.557 INFO Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.8.1
13:24:08.557 INFO Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
13:24:08.557 INFO Mutect2 - Executing as xxx on Linux v3.10.0-1127.18.2.el7.x86_64 amd64
13:24:08.557 INFO Mutect2 - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_192-b12
13:24:08.557 INFO Mutect2 - Start Date/Time: September 25, 2020 1:24:08 PM BST
13:24:08.557 INFO Mutect2 - ------------------------------------------------------------
13:24:08.557 INFO Mutect2 - ------------------------------------------------------------
13:24:08.557 INFO Mutect2 - HTSJDK Version: 2.23.0
13:24:08.557 INFO Mutect2 - Picard Version: 2.22.8
13:24:08.558 INFO Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:24:08.558 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:24:08.558 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:24:08.558 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:24:08.558 INFO Mutect2 - Deflater: IntelDeflater
13:24:08.558 INFO Mutect2 - Inflater: IntelInflater
13:24:08.558 INFO Mutect2 - GCS max retries/reopens: 20
13:24:08.558 INFO Mutect2 - Requester pays: disabled
13:24:08.558 INFO Mutect2 - Initializing engine
13:24:09.048 INFO FeatureManager - Using codec VCFCodec to read file file://ref/1000g_pon.hg38.vcf.gz
13:24:09.207 INFO FeatureManager - Using codec VCFCodec to read file file://ref/af-only-gnomad.hg38.vcf.gz
13:24:09.374 INFO Mutect2 - Done initializing engine
13:24:09.435 INFO NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/GATK/4.1.8.1-GCCcore-9.3.0-Java-1.8/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_utils.so
13:24:09.438 INFO NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/GATK/4.1.8.1-GCCcore-9.3.0-Java-1.8/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
13:24:09.472 INFO IntelPairHmm - Using CPU-supported AVX-512 instructions
13:24:09.472 INFO IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
13:24:09.473 INFO IntelPairHmm - Available threads: 24
13:24:09.473 INFO IntelPairHmm - Requested threads: 4
13:24:09.473 INFO PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
13:24:09.501 INFO ProgressMeter - Starting traversal
13:24:09.502 INFO ProgressMeter - Current Locus Elapsed Minutes Regions Processed Regions/Minute
13:24:19.721 INFO ProgressMeter - chr1:634040 0.2 2460 14443.7
13:24:29.736 INFO ProgressMeter - chr1:1564703 0.3 7220 21409.5
.
.
.
15:28:55.286 INFO ProgressMeter - chrM:12891 124.8 11474080 91967.0
15:29:08.985 INFO VectorLoglessPairHMM - Time spent in setup for JNI call : 10.162159898
15:29:08.986 INFO PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 1047.646162184
15:29:08.986 INFO SmithWatermanAligner - Total compute time in java Smith-Waterman : 1077.35 sec
15:29:08.986 INFO Mutect2 - Shutting down engine
[September 25, 2020 3:29:08 PM BST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 125.01 minutes.
Runtime.totalMemory()=7713325056
java.lang.NullPointerException
at org.broadinstitute.hellbender.transformers.PalindromeArtifactClipReadTransformer.apply(PalindromeArtifactClipReadTransformer.java:98)
at org.broadinstitute.hellbender.transformers.PalindromeArtifactClipReadTransformer.apply(PalindromeArtifactClipReadTransformer.java:49)
at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:42)
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:14)
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.fillCache(PushToPullIterator.java:72)
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.advanceToNextElement(PushToPullIterator.java:58)
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.<init>(PushToPullIterator.java:37)
at org.broadinstitute.hellbender.utils.downsampling.ReadsDownsamplingIterator.<init>(ReadsDownsamplingIterator.java:21)
at org.broadinstitute.hellbender.engine.MultiIntervalLocalReadShard.iterator(MultiIntervalLocalReadShard.java:149)
at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.<init>(AssemblyRegionIterator.java:86)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:188)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6851.  @fleharty

### CODE REVIEW

**Review by fleharty — CHANGES_REQUESTED** [review]
Please create a test that fails on the previous code, and succeeds on the current code.

**Comment by davidbenjamin** [comment]
@fleharty No other reason.  Genevieve requested data from the user and has yet to hear back.

**Comment by davidbenjamin** [comment]
@takutosato We are never going to hear from the user, but it's not a bad bug fix.  Could you review this?

**Review by takutosato — APPROVED** [review]
Looks good!

**Comment by takutosato** [comment]
Review notes:

IMG-0427
:

**Pull request merged**
