### PR TITLE
Add retries on auth failure

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
...and test, naturally.

Issue #3735 reports that transient errors can cause the auth server to return "403 Forbidden" and, in turn, cause us to fail. This PR attempts to work around this situation by retrying a few times on these errors.

### CODE REVIEW

**Comment by droazen** [comment]
@jean-philippe-martin I don't think this should be implemented at the level of the prefetcher -- the prefetcher is not always on when we use NIO. Instead, I'd recommend a patch at the `google-cloud-java` level. If you open a PR against https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes (which is the fork/branch our existing `google-cloud-java` snapshot is built from), we can easily move GATK to a modified snapshot for evaluation.

**Comment by jean-philippe-martin** [comment]
I can't write to your fork; will have to fork it again or something but that'll be another day.

**Comment by droazen** [comment]
@jean-philippe-martin Yeah, just fork my fork and open a PR against that branch, and I'll review.

**Comment by lbergelson** [comment]
@droazen Should we just make an official broad fork?

**Comment by droazen** [comment]
@lbergelson I don't think so -- the need for a fork will be eliminated once https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2453 is resolved.

**Comment by lbergelson** [comment]
It seems likely we will need something similar in the future though.

**Comment by jean-philippe-martin** [comment]
@droazen here's a version that changes the NIO channel directly:

https://github.com/droazen/google-cloud-java/pull/1

Once we get it to a shape we like, I have to remember to also send it upstream.

**Pull request closed without merging**
