### PR TITLE
Remove non-ascii chars from javadoc.

### PR DESCRIPTION
**Pull request by cmnbroad**
Fix https://github.com/broadinstitute/gatk/issues/5934. Remove embedded non-ascii chars from the javadoc, i.e., StrandOddsRatio.java had:

) – ln(
0000000   051 040 342 200 223 040 154 156 050 012

### CODE REVIEW

**Comment by lbergelson** [comment]
@cmnbroad This looks good but I was thinking it would be good to try to fix the problem in the build script so it treats things as utf-8 always instead of being platform specific.  Are you able to reproduce the error locally?

**Comment by cmnbroad** [comment]
@lbergelson No, I've never seen this issue locally. Declaring the encoding rather than leaving it to the platform sounds like a good idea, but if we declare it to always be UTF-8, these non-ASCII UTF-8 chars would be allowed in the source and javadoc (although I guess thats happening now anyway). Other than the rare case where we deliberately need non-ASCII chars for test purposes or such (like I recently needed in the htsjdk VCF 4.3 PR), it would be nice if we could keep them out of the source, especially for cases like this where the displayed glyph is hardly distinguishable from the intended one.

**Comment by lbergelson** [comment]
There have been a few instances like this though.  This one was obviously accidental, but things like the correct spelling of @magicDGS actual name seem like reasonable things to be able to include in the source.  Also, testing non-ascii characters seems like something that is going to be increasingly common as we support new versions of the spec so it seems like we should learn to avoid this problem...

**Comment by cmnbroad** [comment]
@lbergelson Its true, it has happened before. I'll make a separate PR to turn on the UTF-8 encoding and let that run on travis.

**Pull request merged**
