### PR TITLE
Update to GKL version 0.8.8

### PR DESCRIPTION
**Pull request by droazen**

### CODE REVIEW

**Comment by droazen** [comment]
@lbergelson please review

**Comment by lbergelson** [comment]
Oh man. They beat me to it.

**Review by lbergelson — APPROVED** [review]
👍

**Comment by droazen** [comment]
Seeing some test failures unfortunately due to the following error:

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.fs.FileSystem
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
```

**Comment by droazen** [comment]
Added a commit to remove the FPGA PairHMM implementation as an option from GATK, since it's been removed from the GKL.

**Comment by lbergelson** [comment]
We'll see if tests pass.

**Pull request merged**
