### PR TITLE
update hyperlink to new GATK forum page in Readme

### PR DESCRIPTION
**Pull request by SHuang-Broad**

### CODE REVIEW

**Comment by lbergelson** [comment]
@SHuang-Broad Could you update the links in HelpConstants while you're doing this?

**Comment by lbergelson** [comment]
Oh no, there are hundreds of references in the doc to the forums.  We can do that and HelpConstants in a different PR.

**Comment by lbergelson** [comment]
I made a ticket to fix the other ones #6382

**Comment by SHuang-Broad** [comment]
Sorry Louis, wasn't paying attention yesterday.

**Pull request merged**
