### PR TITLE
Remove org.broadinstitute.hellbender.utils.text.parsers in favor of picard classes

### PR DESCRIPTION
**Pull request by magicDGS**
Clean-up after the removal of the Picard-related code.

### CODE REVIEW

**Comment by magicDGS** [comment]
Maybe @cmnbroad is a good reviewer here?

**Comment by cmnbroad** [comment]
@magicDGS This one looks good too, but can you manually rebase this since there is an edit/delete conflict now that #3695 is in (I know I can do it in the UI but I prefer to see the result before I commit!). Thanks.

**Comment by magicDGS** [comment]
Rebased @cmnbroad - back to you!

**Comment by cmnbroad** [comment]
@magicDGS Was about to merge and noticed that it looks like the test files for these tests can be removed as well. Can you verify and include them if so ? Thanks.

**Comment by cmnbroad** [comment]
Thanks again @magicDGS!

**Pull request merged**
