### PR TITLE
Remove what appear to be accidentally added files [VS-834]

### PR DESCRIPTION
**Pull request by mcovarr**

### CODE REVIEW

**Review by rsasch — APPROVED** [review]

**Comment by gbggrant** [comment]
Why do you think these were accidentally added? These look like the chr20 subsetted files that @koncheto-broad uses for his slimmed down quickstart. Might actually be good for a quick testing framework some day. Or I could be completely off base!

**Comment by koncheto-broad** [comment]
Nah, this wasn't me.  It looks like files that Rori added a while ago.

**Comment by mcovarr** [comment]
> Why do you think these were accidentally added?

To be more specific I think the files were not accidentally added, but multiple copies of these files were added in the 050ef8abd378944d3ee6045b2979ecf66529cbb2 commit in May of 2020 and I think the paths I'm removing here were not the intended paths. Copies of these files were added at the root of the GATK repo, under `NA12878`, and under `src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/NA12878`. I'm planning to keep the copies at that last path and move those files to the new repo.

**Review by gbggrant — APPROVED** [review]
Thanks for the context! I do like a good PR that deletes things.

**Pull request merged**
