### PR TITLE
Settable packages for FeatureManager

### PR DESCRIPTION
**Pull request by magicDGS**
Solves #2139

### CODE REVIEW

**Comment by lbergelson** [comment]
@magicDGS We like the idea of making this configurable.  We're not sure that this is the best mechanism for doing so though.  We've been thinking about possibly including a standardized mechanism for configuring properties, i.e. some property file in the jar that could then be overridden by downstream projects.  We don't know a great mechanism for doing that though.  

Do you have any thoughts?  Maybe using something like [commons-configuration](https://commons.apache.org/proper/commons-configuration/userguide/user_guide.html)

It seems like we have a number of places that need this sort of configuration, and it would be good if we had a standard way of doing so instead of relying on little hacks for each instance.

**Comment by droazen** [comment]
See also https://github.com/broadinstitute/gatk/issues/2297

**Comment by magicDGS** [comment]
@lbergelson @droazen, what's about a `GATKConf` class containing settable values? Defaults are the current ones and it's up to the API user if a configuration file or hardcoded solution is implemented, or even command line if they  need it.

**Comment by magicDGS** [comment]
Should I close this PR? Although I would like to have something like this soon...

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/pull/2322

**Pull request closed without merging**
