### PR TITLE
adding spark group to many spark tests

### PR DESCRIPTION
**Pull request by lbergelson**
adding "spark" tag to additional spark tests

### CODE REVIEW

**Comment by lbergelson** [comment]
@droazen please review this one, should be pretty simple :)

**Comment by droazen** [comment]
:+1: merge when ready. Is this all of the spark tests that weren't already marked as in the spark group?

**Comment by lbergelson** [comment]
Not sure... it's all the ones from classes that had failing tests, there are probably more spark related tests...

**Comment by droazen** [comment]
Can you try to tag all the tests in test classes with "spark" in their name? Might as well be thorough..

**Comment by lbergelson** [comment]
fine... so boring...

**Comment by lbergelson** [comment]
think I got em all...

**Comment by lbergelson** [comment]
By got them all, I mean, every `@Test` in every file with spark and test in it's name.  We need a way to automate this..

**Pull request merged**
