### PR TITLE
ChangedCheckPileupDoc

### PR DESCRIPTION
**Pull request by chandrans**
For GATK4 Docs

### CODE REVIEW

**Comment by droazen** [comment]
@chandrans All of these documentation PRs need to mark the tool(s) in question with `@DocumentedFeature`, otherwise no documentation at all will be generated for these tools. See @sooheelee 's PRs in https://github.com/broadinstitute/gatk-protected for an example (eg., https://github.com/broadinstitute/gatk-protected/pull/1073/files)

**Comment by sooheelee** [comment]
Hey @chandrans do you have this?

**Comment by chandrans** [comment]
Nope, missed it in the emails. Thanks for bringing to my attention Soo Hee. Will fix.

**Comment by chandrans** [comment]
Okay, I think I fixed it for this particular tool. Most have the @DocumentedFeature already, but I have to check the rest of the tools

**Comment by sooheelee** [comment]
I had restarted the travis test before but they failed I think because we are missing an import line for the documented feature tag. I went ahead and put one in and let's see if the tests pass.

**Comment by sooheelee** [comment]
Looks like tests pass and this is ready to review.

**Comment by vdauwera** [comment]
will merge when tests pass

**Pull request merged**
