### PR TITLE
Changed location of CNN tools in tool docs

### PR DESCRIPTION
**Pull request by chandrans**
These were in evaluation, but should be in filtering.

### CODE REVIEW

**Comment by ldgauthier** [comment]
@chandrans This doesn't build because the import statement still has VariantFilteringProgramGroup.  That needs to be changed to VariantFilteringProgramGroup in all three files.

**Comment by droazen** [comment]
To phrase it another way, you imported the new program group, but you didn't update the `programGroup = ` line in the `CommandLineProgramProperties` to refer to it.

**Comment by ldgauthier** [comment]
Oops, David is right -- I had it backwards.

**Comment by chandrans** [comment]
I see. Thank you both. Just fixed it and hope it can go in the next release.

**Comment by cmnbroad** [comment]
This looks fine now, but should we also move FilterVariantTranches ? That's also currently in VariantEvaluation.

**Comment by fleharty** [comment]
@chandrans Can you check to see why this is failing tests now?

**Comment by cmnbroad** [comment]
The failures look transient so I'm restarting them.

**Comment by cmnbroad** [comment]
@chandrans does this need to wait for @vdauwera approval or can we merge ?

**Pull request merged**
