### PR TITLE
Add documentation and args check for SVInterval

### PR DESCRIPTION
**Pull request by SHuang-Broad**
@tedsharpe 
not sure if the args checking would significantly affect performance.

### CODE REVIEW

**Comment by SHuang-Broad** [comment]
Then what about the two methods `toSimpleInterval` and `toBedString`?
They are assuming 1-based system, I think.

**Comment by SHuang-Broad** [comment]
@tedsharpe  not sure if this is what you meant.
Also, I think the "ultimate" solution might be marking `SVInterval` not final, but allows it to be extended, and child classes should name themselves with convention baked in.
What do you think?

**Comment by tedsharpe** [comment]
I like this.  Not sure the "ultimate" solution is necessary, but it's certainly reasonable.

**Comment by SHuang-Broad** [comment]
Going to risk it and take the "I like this" as approval :smirk:

**Pull request merged**
