### PR TITLE
Passing implementation of custom ploidy regions in HaplotypeCaller

### PR DESCRIPTION
**Pull request by lbergelson**
@rickymagner

### CODE REVIEW

**Comment by rickymagner** [comment]
So I just updated one of the newer tests, and now all of the tests for HaplotypeCaller seem to be passing locally. The previous commits updating the copy code were preserved when Louis reverted, so there were basically no changes I had to make to get this "working." That does leave us with one question now:

When looking into this a little with James and Louis earlier, we realized that the code for setting up the ActiveRegionGenotyper uses a weird partial copy of the standard CLI args method that has existed in the code for whoever knows how long. Conceptually this seems like a bad idea, but changing it now would possibly cause some older tests to fail, if they were based on this faulty method reasoning.

Should we try to merge the PR as it is now, with all tests passing, and hopefully consistency with previous behavior, or try to update the logic around this genotyper as well at the same time? It's possible we can try to address the latter point as well at some point in the future when we try to get Louis's refactor code actually working. Maybe there could be some quarter goal around a HaplotypeCaller code revamp sometime inspired by some of these ideas?

**Comment by rickymagner** [comment]
And @droazen I think it's correct for the target of this PR to be master. After all, the old PR was always technically just a draft. :smile:

**Comment by droazen** [comment]
@rickymagner I'd recommend postponing any further refactoring for future PRs post-release, in the interests of checkpointing this feature -- assuming that we're confident the feature works as intended and there are no side effects in other HaplotypeCaller codepaths. If the new argument is not already marked as Experimental, perhaps it should be until it's seen some more usage?

**Comment by rickymagner** [comment]
I'd be OK with adding some sort of experimental tag, but I'm not sure where to put it. Does that goes in the docs or somewhere in the code to post a warning to the log? I think the new tests should cover that it's working as intended. There is definitely room for future work (e.g. paying closer around the boundaries, the refactoring ideas, etc), but for now the docs should describe the expected behavior well.

**Comment by lbergelson** [comment]
@rickymagner I think as long as you trust the test this is probably good to go in.  I have some ideas about improvements but I'd say we should leave that for another pr.

**Comment by droazen** [comment]
#carrot(HaplotypeCaller CARROT Regression Tests, VariantCallingCarrotOrchestrated.gatk_docker, )

**Comment by droazen** [comment]
#carrot(HaplotypeCaller CARROT Regression Tests, VariantCallingCarrotOrchestrated.gatk_docker, )

**Comment by droazen** [comment]
The Carrot tests are failing due to issues with R dependencies unrelated to this PR. Since it might take a day to fix, we are debating whether we're comfortable merging this without seeing the full-scale Carrot HaplotypeCaller test results.

**Comment by jamesemery** [comment]
Looks like there was an R error in Carrot. Fortunately the actual meat of the Carrot test ran to completion (for the CHM) I have also checked that this matches for the exome and the NIST sample. I would say that these samples are exactly matching in terms of their VCFeval output and thus we can be confident that this branch did not break the standard pipeline path and we can call this 👍.

```
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SNP | 0.9706 | 0.9863 | 0.9784 | 3473278 | 3489284 | 105213 | 48308 | NA | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-0/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_vcfeval.xml | 539662 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.8814 | 0.8636 | 0.8724 | 485076 | 465627 | 65264 | 73548 | NA | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-0/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_vcfeval.xml | 429205 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
SNP | 0.9743 | 0.99 | 0.9821 | 3384890 | 3391796 | 89358 | 34303 | HCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-1/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_HCR_vcfeval.xml | 474825 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.9117 | 0.9113 | 0.9115 | 276082 | 269292 | 26752 | 26209 | HCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-1/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_HCR_vcfeval.xml | 36612 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
SNP | 0.8454 | 0.8568 | 0.8511 | 87700 | 95535 | 16041 | 15964 | LCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-2/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_LCR_vcfeval.xml | 65355 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.8184 | 0.7901 | 0.804 | 211469 | 201230 | 46925 | 53465 | LCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFControlSample/Benchmark/67f50e9a-e7a3-4b31-9d14-d700b46ddfa5/call-VcfEvalWriteXMLfile/shard-2/CONTROLSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_LCR_vcfeval.xml | 396094 | CONTROLSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
SNP | 0.9706 | 0.9863 | 0.9784 | 3473278 | 3489284 | 105213 | 48308 | NA | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-0/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_vcfeval.xml | 539662 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.8814 | 0.8636 | 0.8724 | 485076 | 465627 | 65264 | 73548 | NA | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-0/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_vcfeval.xml | 429205 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
SNP | 0.9743 | 0.99 | 0.9821 | 3384890 | 3391796 | 89358 | 34303 | HCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-1/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_HCR_vcfeval.xml | 474825 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.9117 | 0.9113 | 0.9115 | 276082 | 269292 | 26752 | 26209 | HCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-1/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_HCR_vcfeval.xml | 36612 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
Type | Precision | Recall | F1_Score | TP_Eval | TP_Base | FP | FN | Stratifier | IGV_Session | UNK | Name | Truth_Set | Summary_Type | Comparison_Engine
SNP | 0.8454 | 0.8568 | 0.8511 | 87700 | 95535 | 16041 | 15964 | LCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-2/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_LCR_vcfeval.xml | 65355 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
INDEL | 0.8184 | 0.7901 | 0.804 | 211469 | 201230 | 46925 | 53465 | LCR | gs://dsde-methods-carrot-prod-cromwell/BenchmarkVCFsHeadToHeadOrchestrated/7012fa81-18fd-4c9c-8722-22c9d7fa642d/call-CHMSampleHeadToHead/BenchmarkComparison/ae3dcac7-7105-4847-ac07-f9f64a43c4c8/call-BenchmarkVCFTestSample/Benchmark/5aa299b6-f2b6-4d42-b478-16a83445bdaa/call-VcfEvalWriteXMLfile/shard-2/TESTSNAPSHOT2018HG002_CHM_GRCh38_SYNDIPv20180222_LCR_vcfeval.xml | 396094 | TESTSNAPSHOT2018HG002 | CHM_GRCh38_SYNDIPv20180222 | summary | VcfEval
```

**Review by droazen — APPROVED** [review]
+1

**Comment by jamesemery** [comment]
#carrot(HaplotypeCaller CARROT Regression Tests, VariantCallingCarrotOrchestrated.gatk_docker, )

**Pull request merged**
