### PR TITLE
Upgrade to Barclay 3.0.0, with changes for FeatureInput discovery based on Barclay refactoring.

### PR DESCRIPTION
**Pull request by cmnbroad**
Will fail until the Barclay upgrade.

### CODE REVIEW

**Comment by droazen** [comment]
@cmnbroad This change seems fine, but this is blocked until the underlying change is merged into barclay and released. Re-assigning to you until that happens.

**Comment by droazen** [comment]
@cmnbroad Can we merge this ancient PR?

**Comment by cmnbroad** [comment]
Unfortunately we can't merge this until we get the corresponding Barclay changes released in Barclay and integrated into GATK.

**Comment by cmnbroad** [comment]
@droazen This is ready to go (needs review, some minor code changes to feature discovery which I think you reviewed a while back).

**Pull request merged**
