### PR TITLE
Move to GenomicsDB 1.0.4 version to get AS_QUALapprox and AS_VarDP fields treated as array of int vectors

### PR DESCRIPTION
**Pull request by nalinigans**
See https://github.com/GenomicsDB/GenomicsDB/commit/10d9ea7ffdfa758a5775a995f9e911a076dbf55e for the relevant changes.

### CODE REVIEW

**Comment by droazen** [comment]
@ldgauthier Mind taking this one for a spin?

**Comment by purod** [comment]
Hi, I downloaded the newest version of GATK ["https://github.com/broadinstitute/gatk.git"], but still got  the following problem as @ldgauthier.

chr01   1660261 .       TCTCTCTCTCTC    TTCTCTCTCTC,T,* 93054.98        .       AC=382,4,2;AF=0.070,7.294e-04,3.647e-04;AN=5484;BaseQRankSum=0.947;DP=21527;ExcessHet=-0.0000;FS=0.000;InbreedingCoeff=0.6279;MLEAC=463,3,1;MLEAF=0.084,5.470e-04,1.823e-04;MQ=58.57;MQRankSum=0.00;QD=27.98;ReadPosRankSum=0.00;SOR=0.533      GT:AD:DP:GQ:PGT:PID:PL:PS       0|1:4,14,0,0:18:99:**0|1:1660261_TC_T**:507,0,114,519,156,675,519,156,675,675:1660261
chr01   1660262 .       C       *,T     6047.70 .       AC=388,26;AF=0.070,4.712e-03;AN=5518;BaseQRankSum=1.38;DP=21571;ExcessHet=-0.0000;FS=0.000;InbreedingCoeff=0.5827;MLEAC=466,19;MLEAF=0.084,3.443e-03;MQ=59.84;MQRankSum=0.00;QD=2.47;ReadPosRankSum=0.431;SOR=0.510     GT:AD:DP:GQ:PGT:PID:PL:PS       0|1:4,14,0:18:99:**0|1:1660261_TC_T**:507,0,114,519,156,675:1660261
chr01   1660263 .       TCTCTCTCTC      TTCTCTCTC,T,*   120442.78       .       AC=102,382,6;AF=0.018,0.069,1.085e-03;AN=5530;BaseQRankSum=0.916;DP=21553;ExcessHet=-0.0000;FS=0.000;InbreedingCoeff=0.6783;MLEAC=119,455,4;MLEAF=0.022,0.082,7.233e-04;MQ=58.72;MQRankSum=0.00;QD=32.35;ReadPosRankSum=0.00;SOR=0.482  GT:AD:DP:GQ:PGT:PID:PL:PS       0|2:4,0,14,0:18:99:**0|1:1660261_TC_T**:507,519,675,0,156,114,519,675,156,675:1660261
chr01   1660264 .       C       *,T     5776.64 .       AC=490,8;AF=0.088,1.440e-03;AN=5556;BaseQRankSum=-5.240e-01;DP=21546;ExcessHet=-0.0000;FS=1.642;InbreedingCoeff=0.6268;MLEAC=587,6;MLEAF=0.106,1.080e-03;MQ=60.00;MQRankSum=0.00;QD=1.85;ReadPosRankSum=-9.670e-01;SOR=0.485    GT:AD:DP:GQ:PGT:PID:PL:PS       0|1:4,14,0:18:99:**0|1:1660261_TC_T**:507,0,114,519,156,675:1660261
chr01   1660265 .       TCTCTCTC        TTC,*,T,TTCTCTC 32340.78        .       AC=80,388,22,4;AF=0.014,0.070,3.951e-03,7.184e-04;AN=5568;BaseQRankSum=1.28;DP=21518;ExcessHet=-0.0000;FS=0.000;InbreedingCoeff=0.7224;MLEAC=91,456,24,3;MLEAF=0.016,0.082,4.310e-03,5.388e-04;MQ=59.16;MQRankSum=0.00;QD=10.31;ReadPosRankSum=1.11;SOR=0.480   GT:AD:DP:GQ:PGT:PID:PL:PS       0|2:4,0,14,0,0:18:99:**0|1:1660261_TC_T**:507,519,675,0,156,114,519,675,156,675,519,675,156,675,675:1660261

**Comment by nalinigans** [comment]
@purod, this is a Pull Request. Would you mind opening up a separate [issue](https://github.com/broadinstitute/gatk/issues/new) for the problem you are seeing with more details about the conflicts you mention?

**Comment by nalinigans** [comment]
@droazen, would it be ok to merge this PR? Thanks.

**Pull request merged**
