### PR TITLE
test query off the contig

### LINKED ISSUE #698: Add a RefAPISource test for a query on an interval that starts on the contig and runs off of it

### PR DESCRIPTION
**Pull request by akiezun**
fixes #698

### CODE REVIEW

**Comment by akiezun** [comment]
for @droazen

**Comment by lbergelson** [comment]
@akiezun back to you with a comment


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISource.java, line 155 \[r1\]](https://reviewable.io:443/reviews/broadinstitute/gatk/1058#-K2OAVk5uR5BT7DB8ujU)** ([raw file](https://github.com/broadinstitute/gatk/blob/a5c03b9e93125bf1acd9e9969a81f236a128ee6d/src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISource.java#L155)):</sup>
Should this be a `UserException`?  It seems like it's probably a bug in the calling code if it's going off the end of a contig, unless you think the likely path is that they've specified the wrong reference.

In either case, I think the message should mention that fewer bases were retrieved than requested in addtion to displaying the interval.

It might be worth making this a more specific exception subclass too, I can imagine potential situations where people would want to catch and handle this differently. 


---

<sup>**[src/test/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISourceUnitTest.java, line 170 \[r1\]](https://reviewable.io:443/reviews/broadinstitute/gatk/1058#-K2OCQKoj0hZv86WbYXu)** ([raw file](https://github.com/broadinstitute/gatk/blob/a5c03b9e93125bf1acd9e9969a81f236a128ee6d/src/test/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISourceUnitTest.java#L170)):</sup>
It would be nice if this were more specific so we can be sure the test isn't passing accidentally due to a failed authentication or downed webserver.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/broadinstitute/gatk/1058)

**Comment by lbergelson** [comment]
+@akiezun 


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/broadinstitute/gatk/1058)

**Comment by akiezun** [comment]
done

**Pull request merged**
