### PR TITLE
Add a mergeWithRemapping() method in ReferenceConfidenceVariantContextMerger to perform allele remapping prior to genotyping

### PR DESCRIPTION
**Pull request by droazen**
This is intended to tide the GVS team over until https://github.com/broadinstitute/gatk/issues/8317 is fixed.

### CODE REVIEW

**Comment by droazen** [comment]
@mcovarr Could you please try the new `ReferenceConfidenceVariantContextMerger.mergeWithRemapping()` method out in the GVS branch, and report whether your tests pass? Should be a drop-in replacement for `ReferenceConfidenceVariantContextMerger.merge()`.

Once https://github.com/broadinstitute/gatk/issues/8317 is fixed, we'll make this behavior the default and ask you to switch back to `merge()`, as discussed recently.

**Comment by droazen** [comment]
@ldgauthier At some point I'd like to discuss both this PR and https://github.com/broadinstitute/gatk/issues/8317 with you

**Comment by droazen** [comment]
(Note that the failure in the cloud tests is expected due to an ongoing GCS bucket region migration -- it should clear up next week)

**Review by mcovarr — APPROVED** [review]
LGTM, thank you! Confirmed that `mergeWithRemapping` works on the GVS / master branch [here](https://github.com/broadinstitute/gatk/pull/8319).

**Pull request merged**
